# Generated by Django 4.2.16 on 2026-01-12 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0007_add_cert_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('migrate', 'Migrate'), ('rotate', 'Rotate'), ('upload', 'Upload'), ('emit', 'Emit')], max_length=32)),
                ('performed_by_identifier', models.CharField(blank=True, help_text='human identifier (username or system user)', max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='fiscal.certificadosefaz')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado Action Audit',
                'verbose_name_plural': 'Certificado Action Audits',
            },
        ),
    ]
