# Generated by Django 4.2.16 on 2026-01-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_add_cert_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoactionaudit',
            name='action',
            field=models.CharField(choices=[('migrate', 'Migrate'), ('rotate', 'Rotate'), ('upload', 'Upload'), ('emit', 'Emit'), ('cancel', 'Cancel'), ('send', 'Send to SEFAZ'), ('callback', 'SEFAZ Callback')], max_length=32),
        ),
    ]
