# Generated by Django 4.2.16 on 2026-01-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_add_estoque_confirmado'),
        ('fiscal', '0009_alter_certificadoactionaudit_action'),
    ]

    operations = [
    ]
