# Generated by Django 4.2.16 on 2026-01-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_add_inss_ir_fields'),
        ('fiscal', '0010_merge_20260116_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostoTrabalhista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fgts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('base_inss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('base_ir', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('folha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_trabalhistas', to='administrativo.folhapagamento')),
            ],
            options={
                'verbose_name': 'Imposto Trabalhista',
                'verbose_name_plural': 'Impostos Trabalhistas',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='ImpostoFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('tipo_imposto', models.CharField(max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('folha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_federais', to='administrativo.folhapagamento')),
                ('folha_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_federais', to='administrativo.folhapagamentoitem')),
            ],
            options={
                'verbose_name': 'Imposto Federal',
                'verbose_name_plural': 'Impostos Federais',
                'ordering': ['-competencia'],
            },
        ),
    ]
