# Generated by Django 4.2.16 on 2026-02-03 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0017_sync_nfes_refinements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arquivoxml',
            new_name='fiscal_arqu_sync_tr_70735d_idx',
            old_name='fiscal_arqu_sync_tr_idx',
        ),
        migrations.RenameIndex(
            model_name='arquivoxml',
            new_name='fiscal_arqu_certifi_9c8fe3_idx',
            old_name='fiscal_arqu_cert_cp_idx',
        ),
        migrations.RenameIndex(
            model_name='eventomanifestacao',
            new_name='fiscal_even_nfe_id_cbbc6c_idx',
            old_name='fiscal_eventomanif_nf_ti_22b8e_idx',
        ),
        migrations.RenameIndex(
            model_name='manifestacao',
            new_name='fiscal_mani_nfe_id_b1250d_idx',
            old_name='fiscal_manifest_nfe_tipo_6b2f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='nferesumo',
            new_name='fiscal_nfer_chave_a_210d79_idx',
            old_name='fiscal_nferes_chave_5d1e2_idx',
        ),
        migrations.AlterField(
            model_name='manifestacao',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
