# Generated by Django 4.2.16 on 2026-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0018_add_a3_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosefaz',
            name='a3_cnpj',
            field=models.CharField(blank=True, help_text='CNPJ for A3 enterprise certificate', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='a3_cpf',
            field=models.CharField(blank=True, help_text='CPF for A3 individual certificate', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='a3_device_serial',
            field=models.CharField(blank=True, help_text='HSM/smartcard device serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='a3_pkcs11_path',
            field=models.CharField(blank=True, help_text='Path to PKCS#11 library (e.g., /usr/lib/libsofthsm2.so)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='tipo',
            field=models.CharField(choices=[('p12', 'PKCS#12 (.p12/.pfx)'), ('a3', 'A3 (PKCS#11 - HSM/Token)')], default='p12', max_length=10),
        ),
    ]
