# Generated by Django 4.2.16 on 2026-02-05 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal', '0019_add_a3_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do certificado', max_length=200)),
                ('ativo', models.BooleanField(default=True, help_text='Certificado ativo para uso')),
                ('arquivo_certificado', models.FileField(help_text='Arquivo .p12 ou .pfx do certificado A3', upload_to='certificados/')),
                ('senha_certificado', models.CharField(help_text='Senha do certificado (será criptografada)', max_length=500)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('cnpj_titular', models.CharField(blank=True, max_length=18, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado A3',
                'verbose_name_plural': 'Certificados A3',
                'ordering': ['-ativo', '-criado_em'],
            },
        ),
    ]
