# Generated by Django 4.2.16 on 2026-02-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0020_certificado_a3'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestacoes', to='fiscal.certificadosefaz'),
        ),
    ]
