# Generated by Django 4.2.16 on 2026-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0021_manifestacao_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Timestamp da última sincronização com SEFAZ (NFeDistribuicaoDFe)', null=True),
        ),
    ]
