# Generated by Django 4.2.16 on 2026-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0022_add_ultima_sincronizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosefaz',
            name='senha_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
