# Generated by Django 4.2.16 on 2026-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0023_add_senha_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosefaz',
            name='cnpj_titular',
            field=models.CharField(blank=True, help_text='CNPJ do titular (detectado automaticamente)', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='cpf_titular',
            field=models.CharField(blank=True, help_text='CPF do titular (detectado automaticamente)', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='nome_titular',
            field=models.CharField(blank=True, help_text='Nome do titular (detectado automaticamente)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='tipo_armazenamento',
            field=models.CharField(blank=True, help_text='A1 ou A3 (detectado automaticamente)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='certificadosefaz',
            name='tipo_certificado',
            field=models.CharField(blank=True, help_text='e-CPF, e-CNPJ, etc. (detectado automaticamente)', max_length=20, null=True),
        ),
    ]
