# Generated by Django 4.2.16 on 2026-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0027_set_unit_price_precision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnfeoverride',
            options={'ordering': ['-criado_em'], 'permissions': (('apply_itemnfeoverride', 'Can apply ItemNFe override'),), 'verbose_name': 'Override Item NFe', 'verbose_name_plural': 'Overrides Itens NFe'},
        ),
        migrations.AlterField(
            model_name='itemnfeoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
