# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('propria', 'Própria'), ('arrendada', 'Arrendada')], default='propria', max_length=10)),
                ('geom', models.TextField(blank=True, help_text='Geometria da área em formato poligonal (JSON)', null=True)),
                ('custo_arrendamento', models.DecimalField(blank=True, decimal_places=2, help_text='Custo de arrendamento em sacas/hectare (apenas para áreas arrendadas)', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='CotacaoSaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco_por_saca', models.DecimalField(decimal_places=2, help_text='Preço em R$ por saca', max_digits=10)),
                ('fonte', models.CharField(default='CEPEA', max_length=100)),
            ],
            options={
                'verbose_name': 'Cotação de Saca',
                'verbose_name_plural': 'Cotações de Saca',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='fazendas.area')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matricula', models.CharField(help_text='Registro/matrícula da fazenda', max_length=100, unique=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to='fazendas.proprietario')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Arrendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('custo_sacas_hectare', models.DecimalField(decimal_places=2, help_text='Custo em sacas/hectare', max_digits=10)),
                ('areas', models.ManyToManyField(blank=True, related_name='arrendamentos', to='fazendas.area')),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos_como_arrendador', to='fazendas.proprietario')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos_como_arrendatario', to='fazendas.proprietario')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos', to='fazendas.fazenda')),
            ],
            options={
                'verbose_name': 'Arrendamento',
                'verbose_name_plural': 'Arrendamentos',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='fazendas.fazenda'),
        ),
        migrations.AddField(
            model_name='area',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='fazendas.proprietario'),
        ),
    ]
