# Generated by Django 4.2.16 on 2025-12-23 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacaosaca',
            options={'ordering': ['-data', 'cultura'], 'verbose_name': 'Cotação de Saca', 'verbose_name_plural': 'Cotações de Saca'},
        ),
        migrations.AddField(
            model_name='cotacaosaca',
            name='cultura',
            field=models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('sorgo', 'Sorgo'), ('trigo', 'Trigo')], default='soja', max_length=10),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Áreas específicas da fazenda que estão sendo arrendadas', related_name='arrendamentos', to='fazendas.area'),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='arrendador',
            field=models.ForeignKey(help_text='Proprietário que CEDE/empresta a terra (dono original)', on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos_como_arrendador', to='fazendas.proprietario'),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='arrendatario',
            field=models.ForeignKey(help_text='Produtor rural que PAGA para usar a terra', on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos_como_arrendatario', to='fazendas.proprietario'),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='custo_sacas_hectare',
            field=models.DecimalField(decimal_places=2, help_text='Custo que o arrendatário paga em sacas de soja por hectare', max_digits=10),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='end_date',
            field=models.DateField(blank=True, help_text='Data de fim do arrendamento (deixe vazio para arrendamento sem prazo)', null=True),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='fazenda',
            field=models.ForeignKey(help_text='Fazenda onde estão as áreas arrendadas (deve pertencer ao arrendador)', on_delete=django.db.models.deletion.CASCADE, related_name='arrendamentos', to='fazendas.fazenda'),
        ),
        migrations.AlterField(
            model_name='arrendamento',
            name='start_date',
            field=models.DateField(help_text='Data de início do arrendamento'),
        ),
    ]
