# Generated by Django 4.2.16 on 2025-12-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0002_add_cultura_to_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='custo_arrendamento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de arrendamento em sacas/hectare (se aplicável)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='geom',
            field=models.TextField(blank=True, help_text='Geometria do talhão em formato poligonal (JSON) - área de trabalho agrícola', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='custo_arrendamento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo geral de arrendamento em sacas/hectare (para áreas arrendadas)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=models.TextField(blank=True, help_text='Geometria da área em formato poligonal (JSON) - agrupamento/matrícula', null=True),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área em hectares (calculada automaticamente se houver geometria)', max_digits=12, null=True),
        ),
    ]
