# Generated by Django 4.2.16 on 2026-02-02 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_transferencia_client_tx_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoArrendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número único do documento de arrendamento', max_length=50, unique=True)),
                ('data_inicio', models.DateField(help_text='Data de início do arrendamento')),
                ('data_fim', models.DateField(help_text='Data de término do arrendamento')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do arrendamento', max_digits=15)),
                ('numero_parcelas', models.PositiveIntegerField(default=1, help_text='Quantidade de parcelas')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', help_text='Periodicidade das parcelas', max_length=20)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arrendador', models.ForeignKey(help_text='Proprietário que cede a terra', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_como_arrendador', to='fazendas.proprietario')),
                ('arrendatario', models.ForeignKey(help_text='Produtor que paga para usar a terra', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_como_arrendatario', to='fazendas.proprietario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_arrendamento_criados', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(help_text='Fazenda onde estão os talhões arrendados', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_arrendamento', to='fazendas.fazenda')),
                ('talhoes', models.ManyToManyField(help_text='Talhões incluídos neste arrendamento', related_name='documentos_arrendamento', to='fazendas.talhao')),
            ],
            options={
                'verbose_name': 'Documento de Arrendamento',
                'verbose_name_plural': 'Documentos de Arrendamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaArrendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(help_text='Número da parcela')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=12)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da parcela')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='fazendas.documentoarrendamento')),
                ('vencimento', models.ForeignKey(blank=True, help_text='Vencimento criado automaticamente no Financeiro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_arrendamento', to='financeiro.vencimento')),
            ],
            options={
                'verbose_name': 'Parcela de Arrendamento',
                'verbose_name_plural': 'Parcelas de Arrendamento',
                'ordering': ['documento', 'numero_parcela'],
                'unique_together': {('documento', 'numero_parcela')},
            },
        ),
    ]
