# Generated by Django 4.2.16 on 2026-02-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissionauditlog_tenant_permissiongroup_tenant'),
        ('fazendas', '0004_documentoarrendamento_parcelaarrendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendamento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='documentoarrendamento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
