# Generated by Django 4.2.16 on 2026-03-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_delegatedpermission_module_and_more'),
        ('fazendas', '0005_arrendamento_tenant_documentoarrendamento_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='matricula',
            field=models.CharField(blank=True, help_text='Matrícula principal (pode deixar vazio e usar múltiplas)', max_length=100),
        ),
        migrations.CreateModel(
            name='MatriculaFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Número da matrícula/registro', max_length=100, unique=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se esta matrícula está ativa')),
                ('data_registro', models.DateField(auto_now_add=True, help_text='Data do registro desta matrícula')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_adicionais', to='fazendas.fazenda')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Matrícula Adicional',
                'verbose_name_plural': 'Matrículas Adicionais',
                'ordering': ['-data_registro'],
            },
        ),
    ]
