# Generated by Django 4.2.16 on 2026-02-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0004_documentoarrendamento_parcelaarrendamento'),
        ('administrativo', '0015_funcionario_bancario'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='Grupos de sistema não podem ser excluídos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Permissão',
                'verbose_name_plural': 'Grupos de Permissão',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Cargo/função do usuário na organização', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fazenda',
            field=models.ForeignKey(blank=True, help_text='Fazenda principal do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='fazendas.fazenda'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='funcionario',
            field=models.OneToOneField(blank=True, help_text='Vínculo com registro de funcionário (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sistema', to='administrativo.funcionario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, default='', help_text='Telefone com DDD (para notificações WhatsApp)', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários')], max_length=30),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DelegatedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_respond', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(help_text='Data/hora de expiração da delegação (obrigatório)')),
                ('is_active', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo da delegação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(help_text='Usuário que delega a permissão', on_delete=django.db.models.deletion.CASCADE, related_name='delegated_permissions_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='Usuário que recebe a permissão', on_delete=django.db.models.deletion.CASCADE, related_name='delegated_permissions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegação de Permissão',
                'verbose_name_plural': 'Delegações de Permissão',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.permissiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atribuição Usuário-Grupo',
                'verbose_name_plural': 'Atribuições Usuário-Grupo',
                'ordering': ['user__username', 'group__nome'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Usuário criado'), ('update_user', 'Usuário atualizado'), ('delete_user', 'Usuário removido'), ('assign_group', 'Atribuído a grupo'), ('remove_group', 'Removido de grupo'), ('create_group', 'Grupo criado'), ('update_group', 'Grupo atualizado'), ('delete_group', 'Grupo removido'), ('grant_permission', 'Permissão concedida'), ('revoke_permission', 'Permissão revogada'), ('update_permission', 'Permissão atualizada'), ('delegate_permission', 'Permissão delegada'), ('revoke_delegation', 'Delegação revogada'), ('access_denied', 'Acesso negado')], max_length=30)),
                ('module', models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários')], default='', max_length=30)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Detalhes da alteração (antes/depois)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='Usuário afetado pela ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria de Permissão',
                'verbose_name_plural': 'Logs de Auditoria de Permissões',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='core_permis_action_9de07b_idx'), models.Index(fields=['user', 'timestamp'], name='core_permis_user_id_d53de6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_respond', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.permissiongroup')),
            ],
            options={
                'verbose_name': 'Permissão de Grupo',
                'verbose_name_plural': 'Permissões de Grupo',
                'ordering': ['group', 'module'],
                'unique_together': {('group', 'module')},
            },
        ),
    ]
