# Generated by Django 4.2.16 on 2026-02-25 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_rbac_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome fantasia ou razão social do cliente', max_length=200)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ no formato 00.000.000/0000-00', max_length=18, null=True, unique=True)),
                ('slug', models.SlugField(help_text='Identificador URL-friendly (ex: fazenda-sao-jose)', max_length=80, unique=True)),
                ('plano', models.CharField(choices=[('basico', 'Básico'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basico', max_length=20)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Tenants inativos não conseguem fazer login')),
                ('limite_usuarios', models.PositiveIntegerField(default=0, help_text='Máximo de usuários (0 = ilimitado)')),
                ('modulos_habilitados', models.JSONField(blank=True, default=list, help_text='Lista de módulos habilitados. Vazio = todos habilitados.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant (Cliente)',
                'verbose_name_plural': 'Tenants (Clientes)',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este usuário pertence. Null = superuser global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.tenant'),
        ),
    ]
