# Generated by Django 4.2.16 on 2026-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissionauditlog_tenant_permissiongroup_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato 000.000.000-00', max_length=14, null=True, unique=True),
        ),
    ]
