# Generated by Django 4.2.16 on 2026-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cpf_to_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='permissiongroup',
            unique_together={('tenant', 'nome')},
        ),
    ]
