# Generated by Django 4.2.16 on 2026-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_actions_permission_to_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatedpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários'), ('actions', 'Isidoro IA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários'), ('actions', 'Isidoro IA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários'), ('actions', 'Isidoro IA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='module',
            field=models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('fazendas', 'Fazendas'), ('agricultura', 'Agricultura'), ('pecuaria', 'Pecuária'), ('estoque', 'Estoque'), ('maquinas', 'Máquinas'), ('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('fiscal', 'Fiscal'), ('comercial', 'Comercial'), ('user_management', 'Gestão de Usuários'), ('actions', 'Isidoro IA')], default='', max_length=30),
        ),
    ]
