# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField()),
                ('quantidade_colhida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='kg', max_length=20)),
                ('qualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('colhida', 'Colhida'), ('armazenada', 'Armazenada em Estoque'), ('comercializada', 'Enviada para Comercial'), ('vendida', 'Vendida')], default='colhida', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ciclo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DismissAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('poda', 'Poda'), ('adubacao', 'Adubação'), ('irrigacao', 'Irrigação'), ('controle_pragas', 'Controle de Pragas'), ('outro', 'Outro')], max_length=20)),
                ('data_manejo', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManejoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_dosagem', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manual', models.BooleanField(default=False)),
                ('tarefa', models.CharField(max_length=200)),
                ('maquina', models.CharField(blank=True, max_length=200)),
                ('insumos', models.JSONField(default=list)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('aprovacao_ia', models.BooleanField(null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_sementes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
