# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agricultura', '0001_initial'),
        ('comercial', '0001_initial'),
        ('fazendas', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantio',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.cultura'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='produto_semente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantios', to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='fazendas.talhao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendas.talhao'),
        ),
        migrations.AddField(
            model_name='manejoproduto',
            name='manejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.manejo'),
        ),
        migrations.AddField(
            model_name='manejoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manejo',
            name='plantio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='agricultura.plantio'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='produtos_utilizados',
            field=models.ManyToManyField(blank=True, through='agricultura.ManejoProduto', to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='talhoes',
            field=models.ManyToManyField(blank=True, related_name='manejos', to='fazendas.talhao'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dismissalert',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.insumo'),
        ),
        migrations.AddField(
            model_name='dismissalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colheita',
            name='carga_comercial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cargaviagem', verbose_name='Carga Comercial'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colheita',
            name='movimentacao_estoque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.movimentacaoestoque', verbose_name='Movimentação de Estoque'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='plantio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas', to='agricultura.plantio'),
        ),
        migrations.AlterUniqueTogether(
            name='dismissalert',
            unique_together={('user', 'insumo')},
        ),
    ]
