# Generated by Django 4.2.16 on 2025-12-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        ('estoque', '0001_initial'),
        ('agricultura', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultura',
            options={'ordering': ['nome'], 'verbose_name': 'Cultura', 'verbose_name_plural': 'Culturas'},
        ),
        migrations.AlterModelOptions(
            name='plantio',
            options={'ordering': ['-data_plantio'], 'verbose_name': 'Plantio', 'verbose_name_plural': 'Plantios'},
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='area_plantada',
        ),
        migrations.AddField(
            model_name='cultura',
            name='tipo',
            field=models.CharField(choices=[('graos', 'Grãos'), ('hortalicas', 'Hortaliças'), ('fruticultura', 'Fruticultura'), ('outros', 'Outros')], default='graos', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='zoneamento_apto',
            field=models.BooleanField(default=True, verbose_name='Zoneamento Apto'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='area_ha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área (ha)'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='fazendas.fazenda', verbose_name='Fazenda'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='ciclo_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ciclo em dias'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.cultura', verbose_name='Cultura'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='data_plantio',
            field=models.DateField(verbose_name='Data do Plantio'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='produto_semente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantios', to='estoque.produto', verbose_name='Produto Semente'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='quantidade_sementes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade de Sementes'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('colhido', 'Colhido'), ('perdido', 'Perdido')], default='planejado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='fazendas.talhao', verbose_name='Talhão'),
        ),
    ]
