# Generated by Django 4.2.16 on 2025-12-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        ('agricultura', '0003_update_cultura_plantio_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantio',
            name='area_ha',
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='talhao',
        ),
        migrations.AddField(
            model_name='plantio',
            name='talhoes',
            field=models.ManyToManyField(related_name='plantios', to='fazendas.talhao', verbose_name='Talhões'),
        ),
    ]
