# Generated by Django 4.2.16 on 2025-12-24 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        ('agricultura', '0004_plantio_multiplos_talhoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='talhao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='fazendas.fazenda', verbose_name='Fazenda'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='talhoes',
            field=models.ManyToManyField(related_name='ordens_servico', to='fazendas.talhao', verbose_name='Talhões'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='aprovacao_ia',
            field=models.BooleanField(null=True, verbose_name='Aprovação IA'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Total'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='insumos',
            field=models.JSONField(default=list, verbose_name='Insumos'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='maquina',
            field=models.CharField(blank=True, max_length=200, verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tarefa',
            field=models.CharField(max_length=200, verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_manual',
            field=models.BooleanField(default=False, verbose_name='Tipo Manual'),
        ),
    ]
