# Generated by Django 4.2.16 on 2025-12-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        ('agricultura', '0005_ordem_servico_multiplos_talhoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejo',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manejos_fazenda', to='fazendas.fazenda'),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='plantio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='agricultura.plantio'),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='tipo',
            field=models.CharField(choices=[('preparo_solo', 'Preparo do Solo'), ('aracao', 'Aração'), ('gradagem', 'Gradagem'), ('subsolagem', 'Subsolagem'), ('correcao_solo', 'Correção do Solo'), ('calagem', 'Calagem'), ('adubacao_base', 'Adubação de Base'), ('adubacao_cobertura', 'Adubação de Cobertura'), ('adubacao_foliar', 'Adubação Foliar'), ('dessecacao', 'Dessecação'), ('plantio_direto', 'Plantio Direto'), ('plantio_convencional', 'Plantio Convencional'), ('irrigacao', 'Irrigação'), ('poda', 'Poda'), ('desbaste', 'Desbaste'), ('amontoa', 'Amontoa'), ('controle_pragas', 'Controle de Pragas'), ('controle_doencas', 'Controle de Doenças'), ('controle_plantas_daninhas', 'Controle de Plantas Daninhas'), ('pulverizacao', 'Pulverização'), ('aplicacao_herbicida', 'Aplicação de Herbicida'), ('aplicacao_fungicida', 'Aplicação de Fungicida'), ('aplicacao_inseticida', 'Aplicação de Inseticida'), ('capina', 'Capina'), ('rocada', 'Roçada'), ('cultivo_mecanico', 'Cultivo Mecânico'), ('outro', 'Outro')], max_length=30),
        ),
    ]
