# Generated by Django 4.2.16 on 2025-12-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_operacao_unificada'),
        ('maquinas', '0001_initial'),
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agricultura', '0006_manejo_fazenda_alter_manejo_plantio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('preparacao', 'Preparação do Solo'), ('adubacao', 'Adubação'), ('plantio', 'Plantio'), ('tratos', 'Tratos Culturais'), ('pulverizacao', 'Pulverização (Fitossanitário)'), ('mecanicas', 'Operações Mecânicas')], max_length=20, verbose_name='Categoria')),
                ('tipo', models.CharField(choices=[('prep_limpeza', 'Limpeza de Área'), ('prep_aracao', 'Aração'), ('prep_gradagem', 'Gradagem'), ('prep_subsolagem', 'Subsolagem'), ('prep_correcao', 'Correção do Solo'), ('adub_base', 'Adubação de Base'), ('adub_cobertura', 'Adubação de Cobertura'), ('adub_foliar', 'Adubação Foliar'), ('plant_dessecacao', 'Dessecação'), ('plant_direto', 'Plantio Direto'), ('plant_convencional', 'Plantio Convencional'), ('trato_irrigacao', 'Irrigação'), ('trato_poda', 'Poda'), ('trato_desbaste', 'Desbaste'), ('trato_amontoa', 'Amontoa'), ('pulv_herbicida', 'Aplicação de Herbicida'), ('pulv_fungicida', 'Aplicação de Fungicida'), ('pulv_inseticida', 'Aplicação de Inseticida'), ('pulv_pragas', 'Controle de Pragas'), ('pulv_doencas', 'Controle de Doenças'), ('pulv_daninhas', 'Controle de Plantas Daninhas'), ('mec_rocada', 'Roçada'), ('mec_cultivo', 'Cultivo Mecânico')], max_length=30, verbose_name='Tipo de Operação')),
                ('data_operacao', models.DateField(verbose_name='Data da Operação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Fim')),
                ('dados_especificos', models.JSONField(blank=True, default=dict, help_text='Campos dinâmicos conforme tipo de operação', verbose_name='Dados Específicos')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Total')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='fazendas.fazenda', verbose_name='Fazenda')),
                ('implemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_implemento', to='maquinas.equipamento', verbose_name='Implemento')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('plantio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='agricultura.plantio', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-data_operacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Dosagem')),
                ('unidade_dosagem', models.CharField(help_text='Ex: L/ha, kg/ha, g/ha', max_length=20, verbose_name='Unidade')),
                ('quantidade_total', models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='Quantidade Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_operacao', to='agricultura.operacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto da Operação',
                'verbose_name_plural': 'Produtos das Operações',
                'unique_together': {('operacao', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='operacao',
            name='produtos',
            field=models.ManyToManyField(blank=True, through='agricultura.OperacaoProduto', to='estoque.produto', verbose_name='Produtos Utilizados'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='talhoes',
            field=models.ManyToManyField(related_name='operacoes', to='fazendas.talhao', verbose_name='Talhões'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='trator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_trator', to='maquinas.equipamento', verbose_name='Trator'),
        ),
        migrations.AddIndex(
            model_name='operacao',
            index=models.Index(fields=['categoria', 'tipo'], name='agricultura_categor_e19691_idx'),
        ),
        migrations.AddIndex(
            model_name='operacao',
            index=models.Index(fields=['data_operacao'], name='agricultura_data_op_bde93e_idx'),
        ),
        migrations.AddIndex(
            model_name='operacao',
            index=models.Index(fields=['status'], name='agricultura_status_fbe601_idx'),
        ),
    ]
