# Generated by Django 4.2.16 on 2025-12-31 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        ('agricultura', '0007_operacao_unificada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColheitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(blank=True, help_text='Colheitadeira', max_length=100, null=True)),
                ('trator', models.CharField(blank=True, max_length=100, null=True)),
                ('basuca', models.CharField(blank=True, help_text='Veículo que recebe do colhedor', max_length=100, null=True)),
                ('quantidade_colhida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('colhido', 'Colhido'), ('em_transporte', 'Em Transporte'), ('descarregado', 'Descarregado')], default='colhido', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colheita Item',
                'verbose_name_plural': 'Colheita Itens',
            },
        ),
        migrations.AlterModelOptions(
            name='colheita',
            options={'ordering': ['-data_colheita'], 'verbose_name': 'Colheita', 'verbose_name_plural': 'Colheitas'},
        ),
        migrations.AddField(
            model_name='colheita',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_combustivel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_maquina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colheita',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='HarvestTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_vehicle', models.CharField(max_length=100)),
                ('to_vehicle', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='agricultura.colheitaitem')),
            ],
            options={
                'verbose_name': 'Transferência de Colheita',
                'verbose_name_plural': 'Transferências de Colheita',
            },
        ),
        migrations.AddField(
            model_name='colheitaitem',
            name='colheita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agricultura.colheita'),
        ),
        migrations.AddField(
            model_name='colheitaitem',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colheita_itens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colheitaitem',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas_itens', to='fazendas.talhao'),
        ),
    ]
