# Generated by Django 4.2.16 on 2026-01-01 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agricultura', '0008_colheitaitem_alter_colheita_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColheitaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('tara', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('custo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colheita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='agricultura.colheita')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporte de Colheita',
                'verbose_name_plural': 'Transportes de Colheita',
            },
        ),
    ]
