# Generated by Django 4.2.16 on 2026-01-02 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0003_add_geom_and_custo_to_talhao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maquinas', '0004_alter_abastecimento_horimetro_km'),
        ('estoque', '0011_remove_movimentacaostatement_statement_prod_criado_idx'),
        ('comercial', '0004_empresa'),
        ('agricultura', '0009_colheitatransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='planejada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_sessions_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamentos', models.ManyToManyField(blank=True, related_name='harvest_sessions', to='maquinas.equipamento')),
                ('equipe', models.ManyToManyField(blank=True, related_name='harvest_sessions', to=settings.AUTH_USER_MODEL)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_sessions', to='agricultura.plantio')),
            ],
            options={
                'verbose_name': 'Sessão de Colheita',
                'verbose_name_plural': 'Sessões de Colheita',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HarvestSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_colhida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('colhido', 'Colhido'), ('em_transporte', 'Em Transporte'), ('carregado', 'Carregado')], default='pendente', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agricultura.harvestsession')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_items', to='fazendas.talhao')),
            ],
            options={
                'verbose_name': 'Item de Sessão de Colheita',
                'verbose_name_plural': 'Itens de Sessão de Colheita',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('motorista', models.CharField(blank=True, max_length=150, null=True)),
                ('tara', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condicoes_graos', models.TextField(blank=True, null=True)),
                ('custo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('destino_tipo', models.CharField(blank=True, choices=[('armazenagem_interna', 'Armazenagem na Propriedade'), ('armazenagem_externa', 'Armazenagem Externa'), ('venda_direta', 'Venda Direta')], max_length=30, null=True)),
                ('contrato_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.empresa')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localarmazenamento')),
                ('session_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='agricultura.harvestsessionitem')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.talhao')),
            ],
            options={
                'verbose_name': 'Movimentação de Carga',
                'verbose_name_plural': 'Movimentações de Carga',
            },
        ),
    ]
