# Generated by Django 4.2.16 on 2026-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0010_harvestsession_harvestsessionitem_movimentacaocarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestsession',
            name='status',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20),
        ),
    ]
