# Generated by Django 4.2.16 on 2026-01-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0009_add_transporte_and_reconciliation'),
        ('agricultura', '0012_add_transporte_and_reconciliation'),
    ]

    operations = [
    ]
