# Generated by Django 4.2.16 on 2026-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0014_add_is_estimada_colheita'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejo',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manejo',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manejo',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manejo',
            name='custo_maquinas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manejo',
            name='custo_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manejo',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='plantio',
            name='contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantio',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plantio',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plantio',
            name='custo_maquinas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plantio',
            name='custo_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plantio',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
