# Generated by Django 4.2.16 on 2026-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0016_add_custo_transporte_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaocarga',
            name='custo_transporte_unidade',
            field=models.CharField(blank=True, choices=[('unidade', 'R$ por Unidade'), ('saca', 'R$ por Saca'), ('tonelada', 'R$ por Tonelada')], default='unidade', max_length=20, null=True),
        ),
    ]
