# Generated by Django 4.2.16 on 2026-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0017_alter_movimentacaocarga_custo_transporte_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Insumos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Mão de Obra'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='custo_maquina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Máquina'),
        ),
    ]
