# Generated by Django 4.2.16 on 2026-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0018_add_custo_breakdown_to_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='unidade_producao',
            field=models.CharField(choices=[('saca_60kg', 'Saca de 60 kg (grãos)'), ('tonelada', 'Tonelada (t)'), ('kg', 'Quilograma (kg)'), ('caixa', 'Caixa / Unidade')], default='tonelada', help_text='Unidade usada para medir a produção (sacas, toneladas, etc.)', max_length=20, verbose_name='Unidade de Produção'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='variedades',
            field=models.TextField(blank=True, help_text='Lista de variedades cultivadas, separadas por vírgula. Ex: M6210, B2801, Nidera 5909', null=True, verbose_name='Variedades'),
        ),
    ]
