# Generated by Django 4.2.16 on 2026-03-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_delegatedpermission_module_and_more'),
        ('agricultura', '0022_cultura_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
