# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('silo', 'Silo'), ('armazem', 'Armazém'), ('galpao', 'Galpão'), ('depósito', 'Depósito'), ('outro', 'Outro')], default='armazem', max_length=20)),
                ('capacidade_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacidade Máxima')),
                ('unidade_capacidade', models.CharField(default='kg', max_length=20, verbose_name='Unidade de Capacidade')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_armazenamento', to='fazendas.fazenda')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('local_armazenamento', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('dosagem_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_dosagem', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('nfe', 'NFe'), ('ordem_servico', 'Ordem de Serviço'), ('colheita', 'Colheita Agrícola'), ('ajuste', 'Ajuste')], default='manual', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.fazenda')),
                ('local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.localarmazenamento', verbose_name='Local de Armazenamento')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.talhao')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('produto', 'numero_lote')},
        ),
    ]
