# Generated by Django 4.2.16 on 2025-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='composicao_quimica',
            field=models.TextField(blank=True, help_text='Fórmula ou composição detalhada do produto', null=True, verbose_name='Composição Química'),
        ),
        migrations.AddField(
            model_name='produto',
            name='principio_ativo',
            field=models.CharField(blank=True, help_text='Ingrediente ativo do produto (ex: Glifosato, Atrazina)', max_length=200, null=True, verbose_name='Princípio Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('semente', 'Semente'), ('fertilizante', 'Fertilizante'), ('corretivo', 'Corretivo'), ('herbicida', 'Herbicida'), ('fungicida', 'Fungicida'), ('inseticida', 'Inseticida'), ('acaricida', 'Acaricida'), ('adjuvante', 'Adjuvante'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dosagem_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dosagem Padrão'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_dosagem',
            field=models.CharField(blank=True, help_text='Ex: L/ha, kg/ha, g/ha', max_length=20, null=True, verbose_name='Unidade de Dosagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo'], name='estoque_pro_codigo_a12776_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='estoque_pro_categor_68c530_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['principio_ativo'], name='estoque_pro_princip_dccbbd_idx'),
        ),
    ]
