# Generated by Django 4.2.16 on 2025-12-25 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0002_operacao_unificada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado'), ('validado', 'Validado'), ('excluido', 'Excluído'), ('movimentacao', 'Movimentação')], max_length=20)),
                ('origem', models.CharField(default='manual', max_length=20)),
                ('nfe_numero', models.CharField(blank=True, max_length=9, null=True)),
                ('nfe_serie', models.CharField(blank=True, max_length=3, null=True)),
                ('nfe_chave_acesso', models.CharField(blank=True, max_length=44, null=True)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('produto_codigo', models.CharField(max_length=50)),
                ('produto_nome', models.CharField(max_length=200)),
                ('produto_categoria', models.CharField(blank=True, max_length=20, null=True)),
                ('produto_unidade', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('validacoes_realizadas', models.JSONField(blank=True, help_text='Lista de validações executadas', null=True)),
                ('alertas', models.JSONField(blank=True, help_text='Alertas gerados durante a operação', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Auditoria de Produto',
                'verbose_name_plural': 'Auditorias de Produtos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['produto', '-criado_em'], name='estoque_pro_produto_d122fe_idx'), models.Index(fields=['acao'], name='estoque_pro_acao_4ed68b_idx'), models.Index(fields=['origem'], name='estoque_pro_origem_dfac06_idx'), models.Index(fields=['nfe_chave_acesso'], name='estoque_pro_nfe_cha_871ccc_idx')],
            },
        ),
    ]
