# Generated by Django 4.2.16 on 2025-12-26 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
        ('estoque', '0003_produtoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='comercial.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
