# Generated by Django 4.2.16 on 2025-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localarmazenamento',
            name='tipo',
            field=models.CharField(choices=[('silo', 'Silo'), ('armazem', 'Armazém'), ('galpao', 'Galpão'), ('depósito', 'Depósito'), ('almoxerifado', 'Almoxarifado'), ('barracao', 'Barracão'), ('patio', 'Pátio'), ('posto', 'Posto de Combustível'), ('outro', 'Outro')], default='armazem', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('semente', 'Semente'), ('fertilizante', 'Fertilizante'), ('corretivo', 'Corretivo'), ('herbicida', 'Herbicida'), ('fungicida', 'Fungicida'), ('inseticida', 'Inseticida'), ('acaricida', 'Acaricida'), ('adjuvante', 'Adjuvante'), ('combustiveis_lubrificantes', 'Combustíveis e Lubrificantes'), ('pecas_manutencao', 'Peças de manutenção'), ('construcao', 'Construção'), ('correcao_solo', 'Correção de solo'), ('outro', 'Outro')], max_length=30, null=True, verbose_name='Categoria'),
        ),
    ]
