# Generated by Django 4.2.16 on 2025-12-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_add_storage_types_and_fuel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='local_armazenamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.localarmazenamento', verbose_name='Local de Armazenamento'),
        ),
    ]
