# Generated by hand: migration to add MovimentacaoStatement model
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_add_local_armazenamento_to_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.DecimalField(max_digits=12, decimal_places=2)),
                ('unidade', models.CharField(max_length=20, null=True, blank=True)),
                ('valor_unitario', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
                ('valor_total', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
                ('data_movimentacao', models.DateTimeField()),
                ('documento_referencia', models.CharField(max_length=100, null=True, blank=True)),
                ('motivo', models.TextField(blank=True)),
                ('observacoes', models.TextField(null=True, blank=True)),
                ('saldo_resultante', models.DecimalField(help_text='Saldo do produto após a movimentação', max_digits=12, decimal_places=2, null=True, blank=True)),
                ('metadata', models.JSONField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='estoque.movimentacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='estoque.produto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='estoque.lote')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.fazenda')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.talhao')),
                ('local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localarmazenamento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customuser')),
            ],
            options={
                'verbose_name': 'Declaração de Movimentação',
                'verbose_name_plural': 'Declarações de Movimentações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='movimentacaostatement',
            index=models.Index(fields=['produto', '-criado_em'], name='estoque_movi_prod_cri_1234ab_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaostatement',
            index=models.Index(fields=['tipo'], name='estoque_movi_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaostatement',
            index=models.Index(fields=['documento_referencia'], name='estoque_movi_docref_idx'),
        ),
    ]
