# Generated by assistant: add cost-related fields to MovimentacaoEstoque and MovimentacaoStatement
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_movimentacao_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='plantio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='agricultura.plantio'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='maquinas.ordemservico'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_alocado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='rateio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.rateiocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='pendente_rateio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_fonte',
            field=models.CharField(blank=True, choices=[('safra', 'Safra'), ('manutencao', 'Manutenção'), ('administrativo', 'Administrativo'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='saldo_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='plantio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='agricultura.plantio'),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='maquinas.ordemservico'),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='custo_alocado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='rateio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.rateiocusto'),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='pendente_rateio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='custo_fonte',
            field=models.CharField(blank=True, choices=[('safra', 'Safra'), ('manutencao', 'Manutenção'), ('administrativo', 'Administrativo'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='saldo_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='saldo_posterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['pendente_rateio'], name='estoque_pendente_rateio_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaostatement',
            index=models.Index(fields=['produto', '-criado_em'], name='statement_prod_criado_idx'),
        ),
    ]
