# Generated by Django 4.2.16 on 2025-12-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0007_operacao_unificada'),
        ('estoque', '0009_add_saldo_posterior_to_movimentacao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimentacaoestoque',
            new_name='estoque_mov_pendent_85243a_idx',
            old_name='estoque_pendente_rateio_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacaostatement',
            new_name='estoque_mov_produto_de955b_idx',
            old_name='estoque_movi_prod_cri_1234ab_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacaostatement',
            new_name='estoque_mov_tipo_f6a529_idx',
            old_name='estoque_movi_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacaostatement',
            new_name='estoque_mov_documen_69a91a_idx',
            old_name='estoque_movi_docref_idx',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='agricultura.operacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_reservada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantidade Reservada'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('reserva', 'Reserva'), ('liberacao', 'Liberação'), ('reversao', 'Reversão')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimentacaostatement',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Dados auxiliares, como validações e alertas gerados', null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaostatement',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('reserva', 'Reserva'), ('liberacao', 'Liberação'), ('reversao', 'Reversão')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', 'data_movimentacao'], name='estoque_mov_produto_583b10_idx'),
        ),
    ]
