# Generated by Django 4.2.16 on 2025-12-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_rename_estoque_pendente_rateio_idx_estoque_mov_pendent_85243a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimentacaostatement',
            name='statement_prod_criado_idx',
        ),
    ]
