# Generated by Django 4.2.16 on 2026-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_expand_movimentacao_estoque'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='estoque_mov_loc_origem_destino_idx',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='localizacao_destino',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='localizacao_origem',
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('reserva', 'Reserva'), ('liberacao', 'Liberação'), ('reversao', 'Reversão')], max_length=10),
        ),
    ]
