# Generated by Django 4.2.16 on 2026-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_remove_movimentacaoestoque_estoque_mov_loc_origem_destino_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('nfe', 'NFe'), ('ordem_servico', 'Ordem de Serviço'), ('colheita', 'Colheita Agrícola'), ('abastecimento', 'Abastecimento'), ('manutencao', 'Manutenção'), ('ajuste', 'Ajuste')], default='manual', max_length=20),
        ),
    ]
