# Generated by Django 4.2.16 on 2026-02-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_add_produto_to_abastecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaostatement',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='estoque.produto'),
        ),
    ]
