# Generated by Django 4.2.16 on 2026-02-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_statement_produto_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaostatement',
            name='produto_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaostatement',
            name='produto_nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
