# Generated by Django 4.2.16 on 2026-02-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_statement_snapshot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoauditoria',
            name='produto_categoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
