# Generated by Django 4.2.16 on 2026-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_alter_produtoauditoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('nfe', 'NFe'), ('ordem_servico', 'Ordem de Serviço'), ('colheita', 'Colheita Agrícola'), ('abastecimento', 'Abastecimento'), ('manutencao', 'Manutenção'), ('agricultura', 'Operação Agrícola'), ('venda', 'Venda'), ('ajuste', 'Ajuste')], default='manual', max_length=20),
        ),
    ]
