# Generated by Django 4.2.16 on 2026-02-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissionauditlog_tenant_permissiongroup_tenant'),
        ('estoque', '0021_localarmazenamento_tipo_local_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='localarmazenamento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='lote',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='produtoarmazenado',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='produtoauditoria',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
