# Generated by Django 4.2.16 on 2026-03-04 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_item_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_tenant__4b393e_idx',
            old_name='actions_ac_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_tenant__5c06c8_idx',
            old_name='actions_ac_tenant_mod_status_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_tenant__ac09c1_idx',
            old_name='actions_ac_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_criado__23470e_idx',
            old_name='actions_ac_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='actions_upl_tenant__874262_idx',
            old_name='actions_up_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='actions_upl_tenant__5da917_idx',
            old_name='actions_up_tenant_module_idx',
        ),
        migrations.AlterField(
            model_name='action',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou/rejeitou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text="Usuário ou 'isidoro' que criou o draft", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='draft_data',
            field=models.JSONField(default=dict, help_text='Payload específico da ação (campos variam por tipo)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='meta',
            field=models.JSONField(default=dict, help_text='Metadados: trace_id, versão, canal de origem (whatsapp/web/upload)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='resultado_execucao',
            field=models.JSONField(default=dict, help_text='Resposta do backend após execução (id criado, status, etc.)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='action',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='Arquivo que originou esta ação (upload em lote)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='actions.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='action',
            name='validation',
            field=models.JSONField(default=dict, help_text='{"warnings": [...], "errors": [...], "is_valid": bool}'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='module',
            field=models.CharField(choices=[('agricultura', 'Agricultura'), ('maquinas', 'Máquinas'), ('estoque', 'Estoque'), ('fazendas', 'Fazendas'), ('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('fiscal', 'Fiscal'), ('administrativo', 'Administrativo')], help_text='Módulo alvo da análise', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
