# Generated by Django 4.2.16 on 2026-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_add_upload_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('criar_proprietario', 'Criar Proprietário'), ('criar_fazenda', 'Criar Fazenda'), ('criar_area', 'Criar Área'), ('criar_talhao', 'Criar Talhão'), ('atualizar_talhao', 'Atualizar Talhão'), ('registrar_arrendamento', 'Registrar Arrendamento'), ('criar_safra', 'Criar Safra / Plantio'), ('operacao_agricola', 'Operação Agrícola'), ('colheita', 'Colheita'), ('movimentacao_carga', 'Movimentação de Carga'), ('registrar_manejo', 'Registrar Manejo'), ('ordem_servico_agricola', 'Ordem de Serviço Agrícola'), ('criar_produto', 'Criar Produto'), ('entrada_estoque', 'Entrada de Estoque'), ('saida_estoque', 'Saída de Estoque'), ('ajuste_estoque', 'Ajuste de Estoque'), ('criar_item_estoque', 'Criar Item de Estoque'), ('movimentacao_interna', 'Movimentação Interna'), ('criar_equipamento', 'Criar Equipamento'), ('manutencao_maquina', 'Manutenção de Máquina'), ('abastecimento', 'Abastecimento'), ('ordem_servico_maquina', 'Ordem de Serviço Máquina'), ('parada_maquina', 'Parada de Máquina')], max_length=50),
        ),
    ]
