# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do equipamento', max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(help_text='Marca/fabricante', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo específico', max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('ano_fabricacao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano de Fabricação')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de Aquisição')),
                ('tipo_equipamento', models.CharField(choices=[('maquina', 'Máquina'), ('implemento', 'Implemento'), ('veiculo', 'Veículo'), ('equipamento', 'Equipamento'), ('ferramenta', 'Ferramenta')], max_length=20, verbose_name='Tipo de Equipamento')),
                ('tipo_motor', models.CharField(choices=[('autopropelido', 'Auto-propelido'), ('estatico', 'Estático')], max_length=15, verbose_name='Tipo de Motor')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Manutenção'), ('vendido', 'Vendido')], default='ativo', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('horimetro_atual', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horímetro Atual (h)')),
                ('capacidade_tanque', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade Tanque (L)')),
                ('consumo_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo Médio (L/h)')),
                ('gps_tracking', models.BooleanField(default=False, verbose_name='GPS Tracking')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa')),
                ('quilometragem_atual', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem Atual (km)')),
                ('local_instalacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Instalação')),
                ('potencia_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potência (kW)')),
                ('tensao_volts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tensão (V)')),
                ('frequencia_hz', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência (Hz)')),
                ('fases', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Fases')),
                ('tipo_maquina', models.CharField(blank=True, choices=[('agricola', 'Agrícola'), ('industrial', 'Industrial'), ('construcao', 'Construção')], max_length=50, null=True, verbose_name='Tipo de Máquina')),
                ('potencia_cv', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potência (CV)')),
                ('largura_trabalho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Largura de Trabalho (m)')),
                ('profundidade_trabalho', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Profundidade Máxima (cm)')),
                ('tipo_implemento', models.CharField(blank=True, choices=[('arado', 'Arado'), ('grade', 'Grade'), ('semeadeira', 'Semeadeira'), ('pulverizador', 'Pulverizador'), ('colheitadeira', 'Colheitadeira')], max_length=50, null=True, verbose_name='Tipo de Implemento')),
                ('capacidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade')),
                ('tipo_veiculo', models.CharField(blank=True, choices=[('caminhao', 'Caminhão'), ('carreta', 'Carreta'), ('utilitario', 'Utilitário'), ('moto', 'Moto')], max_length=50, null=True, verbose_name='Tipo de Veículo')),
                ('capacidade_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade de Carga (kg)')),
                ('numero_eixos', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Eixos')),
                ('categoria_equipamento', models.CharField(blank=True, choices=[('eletrico', 'Elétrico'), ('hidraulico', 'Hidráulico'), ('pneumatico', 'Pneumático'), ('manual', 'Manual')], max_length=50, null=True, verbose_name='Categoria do Equipamento')),
                ('potencia_instalada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potência Instalada')),
                ('dimensoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensões (LxAxP)')),
                ('categoria_ferramenta', models.CharField(blank=True, choices=[('manual', 'Manual'), ('eletrica', 'Elétrica'), ('pneumatica', 'Pneumática')], max_length=50, null=True, verbose_name='Categoria da Ferramenta')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Principal')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('maquina_principal', models.ForeignKey(blank=True, help_text='Máquina à qual este implemento está vinculado', limit_choices_to={'tipo_equipamento': 'maquina'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementos_vinculados', to='maquinas.equipamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True, verbose_name='Número da OS')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('melhoria', 'Melhoria'), ('emergencial', 'Emergencial')], max_length=15, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=15, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('servicos_realizados', models.TextField(blank=True, null=True, verbose_name='Serviços Realizados')),
                ('custo_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo Mão de Obra')),
                ('custo_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo Peças')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='maquinas.equipamento')),
                ('responsavel_abertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_abertas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_executadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(verbose_name='Data do Abastecimento')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade (L)')),
                ('valor_unitario', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário (R$/L)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total (R$)')),
                ('horimetro_km', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horímetro/Km no abastecimento')),
                ('local_abastecimento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local do Abastecimento')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='maquinas.equipamento')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(max_length=100, verbose_name='Tipo de Manutenção')),
                ('intervalo_horas', models.PositiveIntegerField(blank=True, help_text='Intervalo em horas de uso', null=True, verbose_name='Intervalo (horas)')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Intervalo em dias', null=True, verbose_name='Intervalo (dias)')),
                ('ultima_manutencao', models.DateField(blank=True, null=True, verbose_name='Última Manutenção')),
                ('proxima_manutencao', models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('alerta_antecedencia_dias', models.PositiveIntegerField(default=7, verbose_name='Alertar com antecedência (dias)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_preventivas', to='maquinas.equipamento')),
            ],
            options={
                'verbose_name': 'Manutenção Preventiva',
                'verbose_name_plural': 'Manutenções Preventivas',
                'unique_together': {('equipamento', 'tipo_manutencao')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('horimetro', 'Horímetro'), ('quilometragem', 'Quilometragem'), ('manutencao', 'Manutenção'), ('abastecimento', 'Abastecimento')], max_length=20, verbose_name='Tipo de Alerta')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limite')),
                ('unidade', models.CharField(default='horas', max_length=20, verbose_name='Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email_notificacao', models.BooleanField(default=True, verbose_name='Notificar por Email')),
                ('sms_notificacao', models.BooleanField(default=False, verbose_name='Notificar por SMS')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_alerta', to='maquinas.equipamento')),
                ('usuarios_notificar', models.ManyToManyField(blank=True, related_name='alertas_configurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alertas',
                'unique_together': {('equipamento', 'tipo_alerta')},
            },
        ),
    ]
