# Generated by Django 4.2.16 on 2025-12-24 13:48

from django.conf import settings
import django.contrib.gis.db.models.fields as gis_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Trator, Colhedeira, Pivot Central, Bomba de Água', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da categoria', null=True, verbose_name='Descrição')),
                ('tipo_mobilidade', models.CharField(choices=[('autopropelido', 'Autopropelido'), ('estacionario', 'Estacionário'), ('rebocado', 'Rebocado/Implemento')], help_text='Classificação quanto à mobilidade do equipamento', max_length=20, verbose_name='Tipo de Mobilidade')),
                ('requer_horimetro', models.BooleanField(default=False, help_text='Se marcado, horímetro_atual será obrigatório', verbose_name='Requer Horímetro')),
                ('requer_potencia', models.BooleanField(default=False, help_text='Se marcado, potência (kW ou CV) será obrigatória', verbose_name='Requer Potência')),
                ('requer_localizacao', models.BooleanField(default=False, help_text='Se marcado, local_instalacao será obrigatório', verbose_name='Requer Localização')),
                ('requer_acoplamento', models.BooleanField(default=False, help_text='Se marcado, maquina_principal será obrigatória (implementos)', verbose_name='Requer Acoplamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem_exibicao', models.IntegerField(default=0, help_text='Ordem para listagem (menor primeiro)', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='categoria_equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='categoria_ferramenta',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='dimensoes',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='material',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='numero_eixos',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='potencia_instalada',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_implemento',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_maquina',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_motor',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo_veiculo',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='caracteristicas_especificas',
            field=models.JSONField(blank=True, default=dict, help_text='Campos personalizados por categoria (ex: vazao_m3h para bomba, area_irrigada para pivot)', verbose_name='Características Específicas'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='coordenadas',
            field=gis_fields.PointField(blank=True, help_text='Localização GPS do equipamento estacionário', null=True, srid=4326, verbose_name='Coordenadas Geográficas'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='capacidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade genérica (L, kg, sacas, etc)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='horimetro_atual',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Obrigatório se categoria.requer_horimetro=True', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horímetro Atual (h)'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='local_instalacao',
            field=models.CharField(blank=True, help_text='Obrigatório se categoria.requer_localizacao=True', max_length=200, null=True, verbose_name='Local de Instalação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='maquina_principal',
            field=models.ForeignKey(blank=True, help_text='Equipamento ao qual este está acoplado (ex: trator para implemento)', limit_choices_to={'categoria__tipo_mobilidade__in': ['autopropelido', 'estacionario']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementos_vinculados', to='maquinas.equipamento', verbose_name='Equipamento Principal'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='potencia_cv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Obrigatório se categoria.requer_potencia=True', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potência (CV)'),
        ),
        migrations.AddField(
            model_name='categoriaequipamento',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, help_text='Categoria superior (opcional para hierarquia)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='maquinas.categoriaequipamento', verbose_name='Categoria Pai'),
        ),
        migrations.AddField(
            model_name='categoriaequipamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_equipamento_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria flexível do equipamento (Trator, Pivot, Bomba, etc)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='maquinas.categoriaequipamento', verbose_name='Categoria'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['categoria'], name='maquinas_eq_categor_4480d8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status'], name='maquinas_eq_status_ed5309_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['marca', 'modelo'], name='maquinas_eq_marca_b5d0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaequipamento',
            index=models.Index(fields=['tipo_mobilidade'], name='maquinas_ca_tipo_mo_4da6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaequipamento',
            index=models.Index(fields=['ativo'], name='maquinas_ca_ativo_ce6779_idx'),
        ),
    ]
