# Generated by Django 4.2.16 on 2026-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0024_add_auto_detect_cert_fields'),
        ('maquinas', '0001_add_insumos_reservados_prestador_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nfes',
            field=models.ManyToManyField(blank=True, related_name='ordens_servico', to='fiscal.nfe', verbose_name='NFes vinculadas'),
        ),
    ]
