# Generated by Django

from django.db import migrations


def criar_categorias_iniciais(apps, schema_editor):
    """
    Popula o banco com 17 categorias iniciais de equipamentos.
    Inclui máquinas agrícolas tradicionais + equipamentos de irrigação e energia.
    """
    CategoriaEquipamento = apps.get_model('maquinas', 'CategoriaEquipamento')
    
    categorias = [
        # ====================================================================
        # AUTOPROPELIDOS (com propulsão própria)
        # ====================================================================
        {
            'nome': 'Trator',
            'descricao': 'Trator agrícola para tração e operações diversas',
            'tipo_mobilidade': 'autopropelido',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': False,
            'requer_acoplamento': False,
            'ordem_exibicao': 1,
        },
        {
            'nome': 'Colhedeira',
            'descricao': 'Colhedeira automotriz para grãos',
            'tipo_mobilidade': 'autopropelido',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': False,
            'requer_acoplamento': False,
            'ordem_exibicao': 2,
        },
        {
            'nome': 'Pulverizador Autopropelido',
            'descricao': 'Pulverizador automotriz para aplicação de defensivos',
            'tipo_mobilidade': 'autopropelido',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': False,
            'requer_acoplamento': False,
            'ordem_exibicao': 3,
        },
        {
            'nome': 'Caminhão',
            'descricao': 'Caminhão para transporte de carga',
            'tipo_mobilidade': 'autopropelido',
            'requer_horimetro': False,  # Caminhão usa quilometragem
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': False,
            'ordem_exibicao': 4,
        },
        
        # ====================================================================
        # IMPLEMENTOS (rebocados/acoplados)
        # ====================================================================
        {
            'nome': 'Arado',
            'descricao': 'Implemento para preparo primário do solo',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,  # Deve estar acoplado a trator
            'ordem_exibicao': 5,
        },
        {
            'nome': 'Grade',
            'descricao': 'Grade niveladora ou destorroadora',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,
            'ordem_exibicao': 6,
        },
        {
            'nome': 'Plantadeira',
            'descricao': 'Plantadeira ou semeadeira',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,
            'ordem_exibicao': 7,
        },
        {
            'nome': 'Pulverizador Rebocado',
            'descricao': 'Pulverizador acoplado a trator',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,
            'ordem_exibicao': 8,
        },
        {
            'nome': 'Distribuidor de Calcário',
            'descricao': 'Distribuidor para aplicação de corretivos',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,
            'ordem_exibicao': 9,
        },
        {
            'nome': 'Carreta Agrícola',
            'descricao': 'Carreta para transporte interno',
            'tipo_mobilidade': 'rebocado',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': False,
            'requer_acoplamento': True,
            'ordem_exibicao': 10,
        },
        
        # ====================================================================
        # ESTACIONÁRIOS (fixos ou sem mobilidade)
        # ====================================================================
        {
            'nome': 'Pivot Central',
            'descricao': 'Sistema de irrigação por pivot central',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': True,  # Pivot tem horímetro
            'requer_potencia': True,
            'requer_localizacao': True,  # Obrigatório - localização GPS
            'requer_acoplamento': False,
            'ordem_exibicao': 11,
        },
        {
            'nome': 'Bomba de Água',
            'descricao': 'Bomba para irrigação ou abastecimento',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 12,
        },
        {
            'nome': 'Gerador Elétrico',
            'descricao': 'Gerador para fornecimento de energia',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 13,
        },
        {
            'nome': 'Motor Elétrico',
            'descricao': 'Motor elétrico estacionário',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': False,
            'requer_potencia': True,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 14,
        },
        {
            'nome': 'Motor a Combustão',
            'descricao': 'Motor estacionário a diesel ou gasolina',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 15,
        },
        {
            'nome': 'Sistema de Irrigação Fixo',
            'descricao': 'Sistema de irrigação por aspersão ou gotejamento fixo',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': False,
            'requer_potencia': False,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 16,
        },
        {
            'nome': 'Secador de Grãos',
            'descricao': 'Secador estacionário para pós-colheita',
            'tipo_mobilidade': 'estacionario',
            'requer_horimetro': True,
            'requer_potencia': True,
            'requer_localizacao': True,
            'requer_acoplamento': False,
            'ordem_exibicao': 17,
        },
    ]
    
    for cat_data in categorias:
        CategoriaEquipamento.objects.create(**cat_data)
    
    print(f"✅ {len(categorias)} categorias criadas com sucesso!")


def reverter_categorias(apps, schema_editor):
    """Remove as categorias criadas"""
    CategoriaEquipamento = apps.get_model('maquinas', 'CategoriaEquipamento')
    CategoriaEquipamento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_categoria_equipamento_flexivel'),
    ]

    operations = [
        migrations.RunPython(criar_categorias_iniciais, reverter_categorias),
    ]
