# Generated by Django 4.2.16 on 2026-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_abastecimento_tenant_configuracaoalerta_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
    ]
