# Generated by Django 4.2.16 on 2025-12-26 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_popular_categorias_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='horimetro_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horímetro/Km no abastecimento'),
        ),
    ]
