# Generated by Django 4.2.16 on 2026-02-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_add_produto_to_abastecimento'),
        ('maquinas', '0004_alter_abastecimento_horimetro_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='produto_estoque',
            field=models.ForeignKey(blank=True, help_text='Produto do estoque utilizado no abastecimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto'),
        ),
    ]
