# Generated by Django 4.2.16 on 2026-02-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_add_produto_to_abastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='insumos',
            field=models.JSONField(blank=True, default=list, verbose_name='Insumos'),
        ),
    ]
