# Generated by assistant: add CentroCusto and DespesaAdministrativa
from django.db import migrations, models
import django.db.models.deletion


def create_default_centros(apps, schema_editor):
    CentroCusto = apps.get_model('administrativo', 'CentroCusto')
    default = [
        ('BEN', 'Benfeitoria', 'benfeitoria'),
        ('ADM', 'Administrativo', 'administrativo'),
        ('ALIM', 'Alimentação', 'alimentacao'),
        ('TRANS', 'Transporte', 'transporte'),
        ('FRET', 'Frete', 'frete'),
        ('CONS', 'Consultoria', 'consultoria'),
        ('ENER', 'Energia', 'energia'),
        ('AGUA', 'Água', 'agua'),
        ('SEGU', 'Seguro', 'seguro'),
        ('MANU', 'Manutenção', 'manutencao'),
    ]
    for code, name, cat in default:
        CentroCusto.objects.update_or_create(codigo=code, defaults={'nome': name, 'categoria': cat})


def create_rateio_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='financeiro.rateio_approver')


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_initial'),
        ('comercial', '0001_initial'),
        ('agricultura', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(default='administrativo', max_length=50, choices=[('benfeitoria', 'Benfeitoria'), ('administrativo', 'Administrativo'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('frete', 'Frete'), ('consultoria', 'Consultoria'), ('energia', 'Energia'), ('agua', 'Água'), ('seguro', 'Seguro'), ('manutencao', 'Manutenção'), ('outro', 'Outro')])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='administrativo.centrocusto')),
            ],
            options={'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custo', 'ordering': ['codigo']},
        ),
        migrations.CreateModel(
            name='DespesaAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(max_digits=12, decimal_places=2)),
                ('data', models.DateField()),
                ('documento_referencia', models.CharField(max_length=100, null=True, blank=True)),
                ('anexos', models.JSONField(null=True, blank=True)),
                ('pendente_rateio', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='administrativo.centrocusto')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.fornecedor')),
                ('rateio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.rateiocusto')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricultura.plantio')),
            ],
            options={'verbose_name': 'Despesa Administrativa', 'verbose_name_plural': 'Despesas Administrativas', 'ordering': ['-data', '-criado_em']},
        ),
        migrations.AddIndex(
            model_name='despesaadministrativa',
            index=models.Index(fields=['centro', 'data', 'pendente_rateio'], name='administr_cent_data_pend_idx'),
        ),
        migrations.RunPython(create_default_centros),
        migrations.RunPython(create_rateio_group),
    ]
