# Generated by Django 4.2.16 on 2025-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_add_auto_rateio_to_despesa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='despesaadministrativa',
            new_name='administrat_centro__c52f84_idx',
            old_name='administr_cent_data_pend_idx',
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='anexos',
            field=models.JSONField(blank=True, help_text='Metadados de anexos (lista)', null=True),
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
