# Generated by Django 4.2.16 on 2026-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_add_folhaitem_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='criado_por',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.RemoveField(
            model_name='logauditoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='folhapagamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Folha de Pagamento', 'verbose_name_plural': 'Folhas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='folhapagamentoitem',
            options={'verbose_name': 'Item Folha', 'verbose_name_plural': 'Itens Folha'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveIndex(
            model_name='despesaadministrativa',
            name='administrat_centro__c52f84_idx',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='criado_por',
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='anexos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folhapagamentoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
        migrations.DeleteModel(
            name='LogAuditoria',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
