# Generated by Django 4.2.16 on 2026-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_alter_folhapagamento_options_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_titular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave PIX (CPF/CNPJ/telefone/email/EVP)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='recebe_por',
            field=models.CharField(choices=[('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, null=True),
        ),
    ]
