# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0001_initial'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Empréstimo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Empréstimo')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor de Entrada')),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros (%)')),
                ('frequencia_taxa', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Frequência da Taxa')),
                ('metodo_calculo', models.CharField(choices=[('price', 'PRICE (Sistema Francês)'), ('sac', 'SAC (Sistema de Amortização Constante)'), ('personalizado', 'Personalizado')], default='price', max_length=20, verbose_name='Método de Cálculo')),
                ('numero_parcelas', models.PositiveIntegerField(verbose_name='Número de Parcelas')),
                ('prazo_meses', models.PositiveIntegerField(verbose_name='Prazo Total (meses)')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('data_primeiro_vencimento', models.DateField(verbose_name='Primeiro Vencimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Análise')], default='ativo', max_length=20, verbose_name='Status')),
                ('tipo_emprestimo', models.CharField(choices=[('pessoal', 'Pessoal'), ('empresarial', 'Empresarial'), ('rural', 'Rural'), ('consignado', 'Consignado')], default='rural', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('instituicao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.instituicaofinanceira', verbose_name='Instituição Financeira')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fazendas.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_contratacao'],
            },
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Financiamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor de Entrada')),
                ('valor_financiado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Financiado')),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros (%)')),
                ('frequencia_taxa', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Frequência da Taxa')),
                ('metodo_calculo', models.CharField(choices=[('price', 'PRICE (Sistema Francês)'), ('sac', 'SAC (Sistema de Amortização Constante)'), ('personalizado', 'Personalizado')], default='price', max_length=20, verbose_name='Método de Cálculo')),
                ('numero_parcelas', models.PositiveIntegerField(verbose_name='Número de Parcelas')),
                ('prazo_meses', models.PositiveIntegerField(verbose_name='Prazo Total (meses)')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('data_primeiro_vencimento', models.DateField(verbose_name='Primeiro Vencimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Análise')], default='ativo', max_length=20, verbose_name='Status')),
                ('tipo_financiamento', models.CharField(choices=[('custeio', 'Custeio'), ('investimento', 'Investimento'), ('comercializacao', 'Comercialização'), ('industrializacao', 'Industrialização')], default='custeio', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('instituicao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.instituicaofinanceira', verbose_name='Instituição Financeira')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fazendas.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
                'ordering': ['-data_contratacao'],
            },
        ),
        migrations.CreateModel(
            name='RateioCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Rateio')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('data_rateio', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Rateio')),
                ('area_total_hectares', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Total (ha)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Rateio de Custo',
                'verbose_name_plural': 'Rateios de Custos',
                'ordering': ['-data_rateio'],
            },
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], default='despesa', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencimentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fazendas.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Vencimento',
                'verbose_name_plural': 'Vencimentos',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='RateioTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proporcao_area', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Proporção da Área')),
                ('valor_rateado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Rateado')),
                ('rateio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.rateiocusto', verbose_name='Rateio')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendas.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Rateio por Talhão',
                'verbose_name_plural': 'Rateios por Talhão',
                'unique_together': {('rateio', 'talhao')},
            },
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='talhoes',
            field=models.ManyToManyField(through='financeiro.RateioTalhao', to='fazendas.talhao', verbose_name='Talhões'),
        ),
        migrations.CreateModel(
            name='ParcelaFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Juros')),
                ('amortizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Amortização')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Devedor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.financiamento', verbose_name='Financiamento')),
            ],
            options={
                'verbose_name': 'Parcela de Financiamento',
                'verbose_name_plural': 'Parcelas de Financiamentos',
                'ordering': ['numero_parcela'],
                'unique_together': {('financiamento', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Juros')),
                ('amortizacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Amortização')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Devedor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Parcela de Empréstimo',
                'verbose_name_plural': 'Parcelas de Empréstimos',
                'ordering': ['numero_parcela'],
                'unique_together': {('emprestimo', 'numero_parcela')},
            },
        ),
    ]
