# Generated by Django 4.2.16 on 2026-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_add_rateio_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateiotalhao',
            name='proporcao_area',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='Proporção da Área'),
        ),
        migrations.AlterField(
            model_name='rateiotalhao',
            name='valor_rateado',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Rateado'),
        ),
    ]
