# Generated by Django 4.2.16 on 2026-01-15 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0015_manejo_contabilizado_manejo_custo_insumos_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('administrativo', '0014_alter_folhapagamento_options_notificacao'),
        ('financeiro', '0003_auto_20260112_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiocusto',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios', to='administrativo.centrocusto'),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='data_hora_rateio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Rateio'),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='destino',
            field=models.CharField(choices=[('operacional', 'Operacional / Lavoura'), ('manutencao', 'Manutenção'), ('despesa_adm', 'Despesa Administrativa'), ('investimento', 'Investimento'), ('benfeitoria', 'Benfeitoria'), ('financeiro', 'Financeiro / Juros')], default='operacional', max_length=30),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='driver_de_rateio',
            field=models.CharField(choices=[('area', 'Área (ha)'), ('producao', 'Produção (kg)'), ('horas_maquina', 'Horas de Máquina'), ('uniforme', 'Rateio Uniforme')], default='area', max_length=30),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='origem_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='origem_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios', to='agricultura.plantio'),
        ),
        migrations.AlterField(
            model_name='rateiotalhao',
            name='proporcao_area',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Proporção da Área'),
        ),
        migrations.AlterField(
            model_name='rateiotalhao',
            name='valor_rateado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Rateado'),
        ),
        migrations.AddIndex(
            model_name='rateiocusto',
            index=models.Index(fields=['safra'], name='financeiro__safra_i_f2f588_idx'),
        ),
        migrations.AddIndex(
            model_name='rateiocusto',
            index=models.Index(fields=['centro_custo'], name='financeiro__centro__6a182a_idx'),
        ),
        migrations.AddIndex(
            model_name='rateiocusto',
            index=models.Index(fields=['destino'], name='financeiro__destino_8c7451_idx'),
        ),
        migrations.AddIndex(
            model_name='rateiocusto',
            index=models.Index(fields=['data_hora_rateio'], name='financeiro__data_ho_66b6f4_idx'),
        ),
    ]
