# Generated by Django A.I. - manual migration for BankStatementImport and BankTransaction
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0005_contabancaria_lancamentofinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='bank_statements/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('formato', models.CharField(default='csv', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em Processamento'), ('success', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('arquivo_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('rows_count', models.PositiveIntegerField(blank=True, null=True)),
                ('errors_count', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_imports', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='financeiro.contabancaria')),
            ],
            options={
                'verbose_name': 'Importação de Extrato Bancário',
                'verbose_name_plural': 'Importações de Extratos Bancários',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeiro.bankstatementimport')),
            ],
            options={
                'verbose_name': 'Transação de Extrato',
                'verbose_name_plural': 'Transações de Extratos',
            },
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['arquivo_hash'], name='financei_arquivo_hash_1234ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['status'], name='financei_status_1234ab_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['external_id'], name='financei_external_id_1234ab_idx'),
        ),
    ]
