# Generated by GitHub Copilot (manual add)
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_bankstatements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_masked', models.CharField(blank=True, max_length=32, null=True)),
                ('numero_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('validade', models.CharField(blank=True, max_length=7, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='financeiro.contabancaria')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
    ]
