# Generated by Django 4.2.16 on 2026-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_add_numero_contrato'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatementimport',
            new_name='financeiro__arquivo_1e3059_idx',
            old_name='financei_arquivo_hash_1234ab_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementimport',
            new_name='financeiro__status_cab564_idx',
            old_name='financei_status_1234ab_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='financeiro__externa_5993e4_idx',
            old_name='financei_external_id_1234ab_idx',
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['date'], name='financeiro__date_cd83c3_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='financeiro__amount_270028_idx'),
        ),
    ]
