# Generated by Django 4.2.16 on 2026-01-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_compra_valor_cofins_compra_valor_icms_and_more'),
        ('financeiro', '0008_rename_financei_arquivo_hash_1234ab_idx_financeiro__arquivo_1e3059_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='instituicao_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.instituicaofinanceira', verbose_name='Instituição Financeira'),
        ),
    ]
