# Generated by Django 4.2.16 on 2026-01-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_add_creditcard'),
        ('financeiro', '0009_emprestimo_cliente_and_more'),
    ]

    operations = [
    ]
