# Generated by Django 4.2.16 on 2026-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_merge_20260124_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='numero_masked',
            field=models.CharField(blank=True, help_text='Número mascarado (ex: **** **** **** 1234)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='tipo_financiamento',
            field=models.CharField(choices=[('credito_rotativo', 'Crédito Rotativo'), ('custeio', 'Custeio'), ('cpr', 'CPR'), ('investimento', 'Investimento'), ('comercializacao', 'Comercialização'), ('industrializacao', 'Industrialização')], default='custeio', max_length=30, verbose_name='Tipo'),
        ),
    ]
