# Generated by Django 4.2.16 on 2026-01-24 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('financeiro', '0011_alter_creditcard_id_alter_creditcard_numero_masked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamento',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamentos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiamentos_recebidos', to='financeiro.contabancaria', verbose_name='Conta Destino'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='contrato_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='contratos/financiamentos/', verbose_name='Arquivo do Contrato'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='garantias',
            field=models.TextField(blank=True, null=True, verbose_name='Garantias'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='origem_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='origem_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='taxa_mora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Mora (%)'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='taxa_multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Multa (%)'),
        ),
    ]
