# Generated by Django 4.2.16 on 2026-01-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_financiamento_aprovado_em_financiamento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='carencia_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Carência (meses)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='juros_embutidos',
            field=models.BooleanField(default=False, verbose_name='Juros Embutidos na Carência'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='carencia_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Carência (meses)'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='juros_embutidos',
            field=models.BooleanField(default=False, verbose_name='Juros Embutidos na Carência'),
        ),
    ]
