# Generated by Django 4.2.16 on 2026-01-25 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0013_emprestimo_carencia_meses_emprestimo_juros_embutidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transferencia', models.CharField(choices=[('doc', 'DOC'), ('ted', 'TED'), ('pix', 'PIX'), ('interno', 'Transferência Interna')], default='interno', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pix_key_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('pix_key_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('origem_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destino_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='financeiro.contabancaria')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('origem_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data'],
            },
        ),
    ]
