# Generated by Django 4.2.16 on 2026-01-25 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_contabancaria_pix_key_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='client_tx_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='payment_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('settled', 'Liquidada'), ('failed', 'Falhada')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='taxa_bancaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='financeiro.transferencia')),
                ('vencimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='financeiro.vencimento')),
            ],
            options={
                'verbose_name': 'Alocação de Transferência',
                'verbose_name_plural': 'Alocações de Transferências',
                'indexes': [models.Index(fields=['transferencia'], name='financeiro__transfe_fa4510_idx'), models.Index(fields=['vencimento'], name='financeiro__vencime_08e57e_idx')],
            },
        ),
    ]
