# Generated by Django 4.2.16 on 2026-02-02 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0015_transferencia_client_tx_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='data_saldo_inicial',
            field=models.DateField(blank=True, help_text='Data de referência do saldo inicial', null=True, verbose_name='Data do Saldo Inicial'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='tipo_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20, null=True, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AddField(
            model_name='vencimento',
            name='confirmado_extrato',
            field=models.BooleanField(default=False, help_text='Indica se este vencimento foi confirmado através de conciliação bancária', verbose_name='Confirmado no Extrato'),
        ),
        migrations.AddField(
            model_name='vencimento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Conta bancária onde o vencimento foi/será pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencimentos', to='financeiro.contabancaria', verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='vencimento',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencimentos_relacionados', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vencimento',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da transação no extrato bancário', verbose_name='Data da Movimentação')),
                ('descricao', models.TextField(help_text='Descrição da transação conforme extrato', verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], help_text='Débito (saída) ou Crédito (entrada)', max_length=10, verbose_name='Tipo')),
                ('conciliado', models.BooleanField(default=False, help_text='Indica se este item já foi conciliado', verbose_name='Conciliado')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True, verbose_name='Conciliado em')),
                ('arquivo_origem', models.CharField(blank=True, help_text='Nome do arquivo CSV/OFX de origem', max_length=255, null=True, verbose_name='Arquivo de Origem')),
                ('linha_original', models.TextField(blank=True, help_text='Linha original do arquivo para auditoria', null=True, verbose_name='Linha Original')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Conciliado por')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_extrato', to='financeiro.contabancaria', verbose_name='Conta Bancária')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_importados', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('transferencia', models.ForeignKey(blank=True, help_text='Transferência conciliada com este item de extrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_extrato', to='financeiro.transferencia', verbose_name='Transferência Relacionada')),
                ('vencimento', models.ForeignKey(blank=True, help_text='Vencimento conciliado com este item de extrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_extrato', to='financeiro.vencimento', verbose_name='Vencimento Relacionado')),
            ],
            options={
                'verbose_name': 'Item de Extrato Bancário',
                'verbose_name_plural': 'Itens de Extrato Bancário',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['conta_bancaria', 'data'], name='financeiro__conta_b_9a2564_idx'), models.Index(fields=['conciliado', 'data'], name='financeiro__concili_72213a_idx')],
            },
        ),
    ]
