# Generated by Django 4.2.16 on 2026-02-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_contabancaria_data_saldo_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='dia_vencimento_fatura',
            field=models.IntegerField(blank=True, help_text='Dia do mês em que a fatura do cartão vence (1-31)', null=True, verbose_name='Dia do Vencimento da Fatura'),
        ),
    ]
