# Generated by Django 4.2.16 on 2026-02-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0024_add_auto_detect_cert_fields'),
        ('financeiro', '0017_creditcard_dia_vencimento_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='bandeira_codigo',
            field=models.CharField(blank=True, choices=[('01', 'Visa'), ('02', 'Mastercard'), ('03', 'American Express'), ('04', 'Sorocred'), ('05', 'Diners Club'), ('06', 'Elo'), ('07', 'Hipercard'), ('08', 'Aura'), ('09', 'Cabal'), ('99', 'Outros')], help_text='Código tBand da NFe', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='saldo_devedor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor acumulado de compras não faturadas', max_digits=15, verbose_name='Saldo Devedor'),
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('nsu', models.CharField(blank=True, help_text='Código de autorização da transação', max_length=100, null=True, verbose_name='NSU/cAut')),
                ('bandeira_nfe', models.CharField(blank=True, help_text='Código tBand da NFe', max_length=10, null=True)),
                ('faturado', models.BooleanField(default=False, help_text='Se já foi incluído em uma fatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.creditcard')),
                ('nfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cartao', to='fiscal.nfe')),
                ('vencimento_fatura', models.ForeignKey(blank=True, help_text='Vencimento da fatura que incluiu esta transação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cartao', to='financeiro.vencimento')),
            ],
            options={
                'verbose_name': 'Transação de Cartão',
                'verbose_name_plural': 'Transações de Cartão',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
