# Generated by Django 4.2.16 on 2026-02-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_creditcard_bandeira_codigo_creditcard_saldo_devedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='financeiro.contabancaria'),
        ),
    ]
