# Generated by Django 4.2.16 on 2026-02-17 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0028_alter_itemnfeoverride_options_and_more'),
        ('financeiro', '0019_transferencia_conta_destino_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vencimento',
            name='nfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencimentos', to='fiscal.nfe', verbose_name='NFe Vinculada'),
        ),
    ]
