# Generated by Django 4.2.16 on 2026-02-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissionauditlog_tenant_permissiongroup_tenant'),
        ('financeiro', '0020_vencimento_nfe_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='itemextratobancario',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='vencimento',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='rateiocusto',
            name='destino',
            field=models.CharField(choices=[('operacional', 'Operacional / Lavoura'), ('manutencao', 'Manutenção'), ('combustivel', 'Combustível'), ('despesa_adm', 'Despesa Administrativa'), ('investimento', 'Investimento'), ('benfeitoria', 'Benfeitoria'), ('financeiro', 'Financeiro / Juros')], default='operacional', max_length=30),
        ),
    ]
