# Generated by Django 4.2.16 on 2026-02-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cpf_to_tenant'),
        ('financeiro', '0021_bankstatementimport_tenant_banktransaction_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateioapproval',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
