# Generated by Django 4.2.16 on 2026-02-28 17:38

from django.db import migrations


def populate_tenant(apps, schema_editor):
    """Copy tenant from related RateioCusto to RateioApproval"""
    RateioApproval = apps.get_model('financeiro', 'RateioApproval')
    for approval in RateioApproval.objects.all():
        if approval.rateio_id and approval.rateio.tenant_id:
            approval.tenant_id = approval.rateio.tenant_id
            approval.save()


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_rateioapproval_tenant'),
    ]

    operations = [
        migrations.RunPython(populate_tenant, migrations.RunPython.noop),
    ]
