# Generated by Django 4.2.16 on 2026-03-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_localarmazenamento_tenant_localizacao_tenant_and_more'),
        ('core', '0007_add_item_emprestimo'),
        ('financeiro', '0023_populate_rateioapproval_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produtos', to='financeiro.emprestimo', verbose_name='Empréstimo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_itens', to='estoque.produto', verbose_name='Produto')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Item de Empréstimo',
                'verbose_name_plural': 'Itens de Empréstimos',
                'ordering': ['id'],
                'unique_together': {('emprestimo', 'produto')},
            },
        ),
    ]
