import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState, useEffect } from 'react';
import cargasService from '../../services/cargas';
const DiferencasReport = () => {
    const [loading, setLoading] = useState(true);
    const [diferencas, setDiferencas] = useState([]);
    const [limitePercentual, setLimitePercentual] = useState(5);
    const [error, setError] = useState(null);
    useEffect(() => {
        carregarDiferencas();
    }, [limitePercentual]);
    const carregarDiferencas = async () => {
        setLoading(true);
        setError(null);
        try {
            const response = await cargasService.diferencasSignificativas(limitePercentual);
            setDiferencas(response.results);
        }
        catch (err) {
            console.error('Erro ao carregar diferenças:', err);
            setError('Erro ao carregar relatório');
        }
        finally {
            setLoading(false);
        }
    };
    return (_jsx("div", { className: "container-fluid", children: _jsx("div", { className: "row", children: _jsx("div", { className: "col-12", children: _jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsxs("div", { className: "d-flex justify-content-between align-items-center", children: [_jsxs("h3", { className: "card-title", children: [_jsx("i", { className: "bi bi-exclamation-triangle me-2" }), "Diferen\u00E7as Significativas - Peso Estimado vs Balan\u00E7a"] }), _jsxs("div", { className: "d-flex align-items-center gap-2", children: [_jsx("label", { className: "mb-0", children: "Limite:" }), _jsxs("select", { className: "form-select form-select-sm", style: { width: '120px' }, value: limitePercentual, onChange: (e) => setLimitePercentual(Number(e.target.value)), children: [_jsx("option", { value: 2, children: "\u2265 2%" }), _jsx("option", { value: 5, children: "\u2265 5%" }), _jsx("option", { value: 10, children: "\u2265 10%" }), _jsx("option", { value: 15, children: "\u2265 15%" })] })] })] }) }), _jsxs("div", { className: "card-body", children: [error && (_jsxs("div", { className: "alert alert-danger", role: "alert", children: [_jsx("i", { className: "bi bi-exclamation-triangle me-2" }), error] })), loading ? (_jsxs("div", { className: "text-center py-5", children: [_jsx("div", { className: "spinner-border text-primary", role: "status", children: _jsx("span", { className: "visually-hidden", children: "Carregando..." }) }), _jsx("p", { className: "mt-3", children: "Analisando movimenta\u00E7\u00F5es..." })] })) : diferencas.length === 0 ? (_jsxs("div", { className: "alert alert-success text-center", children: [_jsx("i", { className: "bi bi-check-circle me-2" }), "Nenhuma diferen\u00E7a significativa encontrada (\u2265 ", limitePercentual, "%)"] })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "alert alert-warning", children: [_jsx("strong", { children: diferencas.length }), " movimenta\u00E7\u00F5es com diferen\u00E7a \u2265 ", limitePercentual, "%"] }), _jsx("div", { className: "table-responsive", children: _jsxs("table", { className: "table table-hover", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Placa" }), _jsx("th", { className: "text-end", children: "Peso Estimado (kg)" }), _jsx("th", { className: "text-end", children: "Peso Balan\u00E7a (kg)" }), _jsx("th", { className: "text-end", children: "Diferen\u00E7a (kg)" }), _jsx("th", { className: "text-end", children: "Diferen\u00E7a (%)" }), _jsx("th", { children: "Data" })] }) }), _jsx("tbody", { children: diferencas.map((diff, index) => {
                                                            const isPositivo = diff.diferenca > 0;
                                                            const percentualAbs = Math.abs(diff.percentual);
                                                            return (_jsxs("tr", { children: [_jsx("td", { children: _jsx("strong", { children: diff.placa }) }), _jsx("td", { className: "text-end", children: diff.peso_estimado.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }), _jsx("td", { className: "text-end", children: diff.peso_balanca.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }), _jsx("td", { className: "text-end", children: _jsxs("span", { className: isPositivo ? 'text-success' : 'text-danger', children: [isPositivo ? '+' : '', diff.diferenca.toLocaleString('pt-BR', { minimumFractionDigits: 2 })] }) }), _jsx("td", { className: "text-end", children: _jsxs("span", { className: `badge ${percentualAbs >= 10 ? 'bg-danger' : 'bg-warning'}`, children: [isPositivo ? '+' : '', diff.percentual.toFixed(2), "%"] }) }), _jsx("td", { children: new Date(diff.data).toLocaleString('pt-BR') })] }, index));
                                                        }) }), _jsx("tfoot", { children: _jsxs("tr", { className: "table-secondary", children: [_jsx("th", { children: "Total" }), _jsx("th", { className: "text-end", children: diferencas.reduce((sum, d) => sum + d.peso_estimado, 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }), _jsx("th", { className: "text-end", children: diferencas.reduce((sum, d) => sum + d.peso_balanca, 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }), _jsx("th", { className: "text-end", children: diferencas.reduce((sum, d) => sum + d.diferenca, 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }), _jsx("th", { colSpan: 2 })] }) })] }) }), _jsxs("div", { className: "mt-4", children: [_jsx("h5", { children: "Distribui\u00E7\u00E3o de Diferen\u00E7as" }), _jsxs("div", { className: "row", children: [_jsx("div", { className: "col-md-4", children: _jsx("div", { className: "card bg-success text-white", children: _jsxs("div", { className: "card-body text-center", children: [_jsx("h6", { children: "Sobra (Peso Real > Estimado)" }), _jsx("h3", { children: diferencas.filter(d => d.diferenca > 0).length }), _jsx("small", { children: "movimenta\u00E7\u00F5es" })] }) }) }), _jsx("div", { className: "col-md-4", children: _jsx("div", { className: "card bg-danger text-white", children: _jsxs("div", { className: "card-body text-center", children: [_jsx("h6", { children: "Falta (Peso Real < Estimado)" }), _jsx("h3", { children: diferencas.filter(d => d.diferenca < 0).length }), _jsx("small", { children: "movimenta\u00E7\u00F5es" })] }) }) }), _jsx("div", { className: "col-md-4", children: _jsx("div", { className: "card bg-primary text-white", children: _jsxs("div", { className: "card-body text-center", children: [_jsx("h6", { children: "Diferen\u00E7a M\u00E9dia" }), _jsxs("h3", { children: [(diferencas.reduce((sum, d) => sum + Math.abs(d.percentual), 0) / diferencas.length).toFixed(2), "%"] }), _jsx("small", { children: "percentual" })] }) }) })] })] })] }))] })] }) }) }) }));
};
export default DiferencasReport;
