import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useApiQuery, useApiDelete } from '@/hooks/useApi';
const CentrosCustoList = ({ onOpenCreate }) => {
    const { data: centros = [], isLoading, error, refetch } = useApiQuery(['centros-custo'], '/administrativo/centros-custo/');
    const deleteMut = useApiDelete('/administrativo/centros-custo/', [['centros-custo']]);
    return (_jsxs("div", { children: [_jsxs("div", { className: "d-flex justify-content-between mb-2", children: [_jsx("div", { children: _jsx("strong", { children: "Centros de Custo" }) }), _jsxs("div", { children: [_jsxs("button", { className: "btn btn-sm btn-outline-secondary me-2", onClick: () => refetch(), children: [_jsx("i", { className: "bi bi-arrow-clockwise" }), " Atualizar"] }), _jsxs("button", { className: "btn btn-sm btn-primary", onClick: () => onOpenCreate && onOpenCreate(), children: [_jsx("i", { className: "bi bi-plus" }), " Novo"] })] })] }), isLoading && _jsx("div", { children: "Carregando..." }), error && _jsx("div", { className: "text-danger", children: "Erro ao carregar centros" }), centros.length === 0 && !isLoading && _jsx("div", { className: "text-muted", children: "Nenhum centro cadastrado." }), centros.length > 0 && (_jsx("div", { className: "table-responsive", children: _jsxs("table", { className: "table table-hover", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "#" }), _jsx("th", { children: "C\u00F3digo" }), _jsx("th", { children: "Nome" }), _jsx("th", { children: "Categoria" }), _jsx("th", { children: "Ativo" }), _jsx("th", { children: "A\u00E7\u00F5es" })] }) }), _jsx("tbody", { children: centros.map(c => (_jsxs("tr", { children: [_jsx("td", { children: c.id }), _jsx("td", { children: c.codigo }), _jsx("td", { children: c.nome }), _jsx("td", { children: c.categoria }), _jsx("td", { children: c.ativo ? _jsx("span", { className: "badge bg-success", children: "Sim" }) : _jsx("span", { className: "badge bg-secondary", children: "N\u00E3o" }) }), _jsx("td", { children: _jsx("button", { className: "btn btn-sm btn-danger", onClick: () => { if (window.confirm('Remover centro?'))
                                                deleteMut.mutate(c.id); }, children: "Remover" }) })] }, c.id))) })] }) }))] }));
};
export default CentrosCustoList;
