import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useApiQuery, useApiDelete } from '@/hooks/useApi';
import FuncionarioForm from './FuncionarioForm';
const FuncionariosList = () => {
    const { data: funcionarios = [], isLoading, error, refetch } = useApiQuery(['funcionarios'], '/administrativo/funcionarios/');
    const deleteMut = useApiDelete('/administrativo/funcionarios/', [['funcionarios']]);
    const [open, setOpen] = React.useState(false);
    const [editing, setEditing] = React.useState(null);
    return (_jsxs("div", { children: [_jsxs("div", { className: "d-flex justify-content-between mb-2", children: [_jsx("div", { children: _jsx("strong", { children: "Funcion\u00E1rios" }) }), _jsxs("div", { children: [_jsxs("button", { className: "btn btn-sm btn-outline-secondary me-2", onClick: () => refetch(), children: [_jsx("i", { className: "bi bi-arrow-clockwise" }), " Atualizar"] }), _jsxs("button", { className: "btn btn-sm btn-primary", onClick: () => { setEditing(null); setOpen(true); }, children: [_jsx("i", { className: "bi bi-plus" }), " Novo"] })] })] }), isLoading && _jsx("div", { children: "Carregando..." }), error && _jsx("div", { className: "text-danger", children: "Erro ao carregar funcion\u00E1rios" }), funcionarios.length === 0 && !isLoading && _jsx("div", { className: "text-muted", children: "Nenhum funcion\u00E1rio cadastrado." }), funcionarios.length > 0 && (_jsx("div", { className: "table-responsive", children: _jsxs("table", { className: "table table-hover", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "#" }), _jsx("th", { children: "Nome" }), _jsx("th", { children: "Cargo" }), _jsx("th", { children: "Sal\u00E1rio" }), _jsx("th", { children: "Ativo" }), _jsx("th", { children: "A\u00E7\u00F5es" })] }) }), _jsx("tbody", { children: funcionarios.map(f => (_jsxs("tr", { children: [_jsx("td", { children: f.id }), _jsx("td", { children: f.nome }), _jsx("td", { children: f.cargo || '-' }), _jsx("td", { children: f.salario_bruto ? `R$ ${f.salario_bruto}` : '-' }), _jsx("td", { children: f.ativo ? _jsx("span", { className: "badge bg-success", children: "Sim" }) : _jsx("span", { className: "badge bg-secondary", children: "N\u00E3o" }) }), _jsxs("td", { children: [_jsx("button", { className: "btn btn-sm btn-outline-secondary me-1", onClick: () => { setEditing(f); setOpen(true); }, children: "Editar" }), _jsx("button", { className: "btn btn-sm btn-danger", onClick: () => { if (window.confirm('Remover funcionário?'))
                                                    deleteMut.mutate(f.id); }, children: "Remover" })] })] }, f.id))) })] }) })), open && (_jsx("div", { className: "modal d-block", tabIndex: -1, role: "dialog", children: _jsx("div", { className: "modal-dialog", role: "document", children: _jsxs("div", { className: "modal-content", children: [_jsxs("div", { className: "modal-header", children: [_jsx("h5", { className: "modal-title", children: editing ? 'Editar Funcionário' : 'Novo Funcionário' }), _jsx("button", { type: "button", className: "btn-close", "aria-label": "Close", onClick: () => setOpen(false) })] }), _jsx("div", { className: "modal-body", children: _jsx(FuncionarioForm, { onClose: () => { setOpen(false); setEditing(null); }, initialData: editing }) })] }) }) }))] }));
};
export default FuncionariosList;
