# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agricultura', '0002_initial'),
        ('fazendas', '0001_initial'),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendacolheita',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='silobolsa',
            name='carga_viagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercial.cargaviagem', verbose_name='Carga de Viagem'),
        ),
        migrations.AddField(
            model_name='silobolsa',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestadores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='instituicaofinanceira',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituicoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricantes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='colheita_agricola',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricultura.colheita', verbose_name='Colheita Agrícola'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.cultura', verbose_name='Cultura'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendas.fazenda', verbose_name='Fazenda'),
        ),
    ]
