# Generated by Django 4.2.16 on 2025-12-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_remove_movimentacaostatement_statement_prod_criado_idx'),
        ('comercial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaviagem',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Motorista'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='gross_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='tare_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Tare (kg)'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='truck_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa do Caminhão'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='unload_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloads', to='estoque.localarmazenamento', verbose_name='Local de Descarregamento'),
        ),
        migrations.AddField(
            model_name='cargaviagem',
            name='unload_movimentacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_unload', to='estoque.movimentacaoestoque', verbose_name='Movimentacao de Descarregamento'),
        ),
    ]
