# Generated by Django A.I. - DespesaPrestadora model migration
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_empresa'),
        ('administrativo', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaPrestadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da despesa')),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte'), ('mecanica', 'Mecânica'), ('servico', 'Serviço'), ('material', 'Material'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_prestadoras_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='comercial.empresa')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='comercial.prestadorservico')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='administrativo.centrocusto')),
            ],
            options={
                'verbose_name': 'Despesa Prestadora',
                'verbose_name_plural': 'Despesas Prestadoras',
                'ordering': ['-data', 'empresa'],
            },
        ),
        migrations.AddIndex(
            model_name='despesaprestadora',
            index=models.Index(fields=['empresa', 'data'], name='comercial_despesa_empresa_data_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaprestadora',
            index=models.Index(fields=['empresa', 'categoria', 'data'], name='comercial_despesa_empresa_cat_data_idx'),
        ),
    ]