# Generated by Django 4.2.16 on 2026-01-06 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0008_add_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='rascunho', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('partes', models.JSONField(blank=True, null=True)),
                ('itens', models.JSONField(blank=True, null=True)),
                ('condicoes', models.JSONField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RenameIndex(
            model_name='despesaprestadora',
            new_name='comercial_d_empresa_40d304_idx',
            old_name='comercial_despesa_empresa_data_idx',
        ),
        migrations.RenameIndex(
            model_name='despesaprestadora',
            new_name='comercial_d_empresa_3841f3_idx',
            old_name='comercial_despesa_empresa_cat_data_idx',
        ),
        migrations.AlterField(
            model_name='compra',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
