# Generated by Django 4.2.16 on 2026-01-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_add_contrato'),
        ('comercial', '0009_contrato_and_more'),
    ]

    operations = [
    ]
