# Generated by Django 4.2.16 on 2026-01-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0010_merge_0007_add_contrato_0009_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('insumos', 'Insumos Agrícolas'), ('maquinas', 'Máquinas e Equipamentos'), ('servicos', 'Serviços'), ('transporte', 'Transporte'), ('consultoria', 'Consultoria'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='documentos_pendentes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Documentos Pendentes'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='total_compras',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total de Compras'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ultima_compra',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Última Compra'),
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('status_alterado', 'Status Alterado'), ('documento_adicionado', 'Documento Adicionado'), ('documento_removido', 'Documento Removido'), ('pagamento_registrado', 'Pagamento Registrado')], max_length=25, verbose_name='Tipo de Alteração')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('alterado_em', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_fornecedor', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='comercial.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('certificado', 'Certificado'), ('licenca', 'Licença'), ('autorizacao', 'Autorização'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_renovacao', models.DateField(blank=True, null=True, verbose_name='Data de Renovação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vencido', 'Vencido'), ('expirando', 'Expirando'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status')),
                ('dias_alerta', models.PositiveIntegerField(default=30, verbose_name='Dias para Alerta de Vencimento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_fornecedores/', verbose_name='Arquivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fornecedor_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='comercial.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Documento de Fornecedor',
                'verbose_name_plural': 'Documentos de Fornecedores',
                'ordering': ['-data_vencimento', 'titulo'],
            },
        ),
    ]
