# Generated by Django 4.2.16 on 2026-01-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0011_impostotrabalhista_impostofederal'),
        ('comercial', '0015_add_inscricao_estadual_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='nfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='fiscal.nfe'),
        ),
        migrations.AddField(
            model_name='compra',
            name='xml_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('venda_futura', 'Venda Futura'), ('venda_spot', 'Venda Spot'), ('bater', 'Bater'), ('servico', 'Serviço'), ('fornecimento', 'Fornecimento'), ('parceria', 'Parceria'), ('outros', 'Outros')], default='compra', max_length=50),
        ),
    ]
