# Generated by Django 4.2.16 on 2026-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_compra_nfe_compra_xml_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='valor_cofins',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_icms',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_pis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
