# Generated by Django 4.2.16 on 2026-02-16 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_add_vendacontrato_parcelacontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='agencia_bancaria',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='conta_bancaria',
            field=models.CharField(blank=True, max_length=30, verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='titular_conta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titular da Conta'),
        ),
        migrations.AlterField(
            model_name='documentofornecedor',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
    ]
