# Generated by Django 4.2.16 on 2026-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_cargaviagem_tenant_cliente_tenant_compra_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prazo_execucao_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo de Execução (dias)'),
        ),
    ]
