# Generated by Django 4.2.16 on 2026-03-02 08:55

from django.db import migrations
from django.db.models import Q


def remove_test_institutions(apps, schema_editor):
    """Remove E2E and test institutions"""
    InstituicaoFinanceira = apps.get_model('comercial', 'InstituicaoFinanceira')
    
    # Remove all E2E and test institutions
    test_institutions = InstituicaoFinanceira.objects.filter(
        Q(nome__istartswith='E2E') |
        Q(nome__icontains='Inst Test') |
        Q(codigo_bacen__in=['403284', '430233', '516096', '543661', '999', '0001', '0002'])
    )
    
    deleted_count = test_institutions.delete()[0]
    print(f"✓ Removed {deleted_count} test institutions")


def reverse_remove_test_institutions(apps, schema_editor):
    """No-op reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0022_populate_financial_institutions'),
    ]

    operations = [
        migrations.RunPython(remove_test_institutions, reverse_remove_test_institutions),
    ]
