# Generated by Django 4.2.16 on 2026-03-02 08:57

from django.db import migrations


def remove_banco_e2e_institutions(apps, schema_editor):
    """Remove all Banco E2E test institutions"""
    InstituicaoFinanceira = apps.get_model('comercial', 'InstituicaoFinanceira')
    
    # Remove all institutions with "Banco E2E" in the name
    e2e_banks = InstituicaoFinanceira.objects.filter(nome__icontains='Banco E2E')
    deleted_count = e2e_banks.delete()[0]
    print(f"✓ Removed {deleted_count} Banco E2E institutions")


def reverse_remove_banco_e2e(apps, schema_editor):
    """No-op reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_remove_test_institutions'),
    ]

    operations = [
        migrations.RunPython(remove_banco_e2e_institutions, reverse_remove_banco_e2e),
    ]
