# Generated by Django 4.2.16 on 2026-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0025_add_comprehensive_financial_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('venda_futura', 'Venda Futura'), ('venda_spot', 'Venda Spot'), ('bater', 'Barter'), ('servico', 'Serviço'), ('fornecimento', 'Fornecimento'), ('parceria', 'Parceria'), ('outros', 'Outros')], default='compra', max_length=50),
        ),
    ]
