# Generated by Django 4.2.16 on 2025-12-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO code, ex: pt-BR', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Human readable name, ex: Português (Brasil)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the language is available for users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
