# Generated by Django 4.2.16 on 2026-03-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_delegatedpermission_module_and_more'),
        ('fazendas', '0005_arrendamento_tenant_documentoarrendamento_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHUVA_FORTE', 'Chuva Forte'), ('GRANIZO', 'Granizo'), ('VENTO_FORTE', 'Vento Forte'), ('GEADA', 'Geada'), ('ESTIAGEM', 'Estiagem'), ('RAIO', 'Raio/Tempestade')], help_text='Tipo de alerta', max_length=50)),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('descricao', models.TextField(help_text='Descrição do alerta')),
                ('data_inicio_prevista', models.DateTimeField(help_text='Quando o alerta começa')),
                ('data_fim_prevista', models.DateTimeField(help_text='Quando o alerta termina')),
                ('ativo', models.BooleanField(default=True)),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='fazendas.talhao')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Alerta de Clima',
                'verbose_name_plural': 'Alertas de Clima',
                'ordering': ['-data_inicio_prevista'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude da previsão (EPSG:4326)')),
                ('longitude', models.FloatField(help_text='Longitude da previsão (EPSG:4326)')),
                ('municipio', models.CharField(blank=True, help_text='Nome do município/cidade', max_length=200)),
                ('temperatura_atual', models.FloatField(help_text='Temperatura atual em °C')),
                ('temperatura_sensacao', models.FloatField(blank=True, help_text='Sensação térmica em °C', null=True)),
                ('umidade_atual', models.IntegerField(help_text='Umidade relativa em %')),
                ('condicao_atual', models.CharField(help_text='Condição do clima (Sunny, Rainy, Cloudy, etc)', max_length=50)),
                ('descricao_clima', models.TextField(blank=True, help_text='Descrição detalhada da condição')),
                ('vento_velocidade', models.FloatField(help_text='Velocidade do vento em km/h')),
                ('vento_direcao', models.IntegerField(blank=True, help_text='Direção do vento em graus (0-360)', null=True)),
                ('indice_uv', models.FloatField(blank=True, help_text='Índice UV (0-11+)', null=True)),
                ('ponto_orvalho', models.FloatField(blank=True, help_text='Ponto de orvalho em °C', null=True)),
                ('pressao', models.FloatField(blank=True, help_text='Pressão atmosférica em hPa', null=True)),
                ('visibilidade', models.IntegerField(blank=True, help_text='Visibilidade em metros', null=True)),
                ('cobertura_nuvens', models.IntegerField(blank=True, help_text='Cobertura de nuvens em %', null=True)),
                ('chance_precipitacao', models.IntegerField(blank=True, help_text='Chance de precipitação em %', null=True)),
                ('forecast_7dias', models.JSONField(blank=True, default=list, help_text='Previsão para próximos 7 dias em formato JSON')),
                ('risco_doenca_fungica', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], default='BAIXO', help_text='Risco de doença fúngica', max_length=20)),
                ('recomendacao_pulverizacao', models.TextField(blank=True, help_text='Recomendação sobre pulverização')),
                ('indice_aridez', models.FloatField(blank=True, help_text='Índice de aridez para irrigação', null=True)),
                ('data_previsao', models.DateTimeField(auto_now_add=True, help_text='Data/hora da última atualização')),
                ('proxima_atualizacao', models.DateTimeField(blank=True, help_text='Próxima data de atualização agendada', null=True)),
                ('fonte_dados', models.CharField(default='openweathermap', help_text='Fonte dos dados (API usada)', max_length=50)),
                ('talhao', models.ForeignKey(blank=True, help_text='Talhão cuja previsão se refere', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='fazendas.talhao')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Previsão de Clima',
                'verbose_name_plural': 'Previsões de Clima',
                'ordering': ['-data_previsao'],
                'indexes': [models.Index(fields=['talhao', '-data_previsao'], name='agricultura_talhao__7560ac_idx'), models.Index(fields=['latitude', 'longitude', '-data_previsao'], name='agricultura_latitud_c07c6d_idx')],
            },
        ),
    ]
