# Generated by Django 4.2.16 on 2026-03-14 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_delegatedpermission_module_and_more'),
        ('agricultura_weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da cidade', max_length=200)),
                ('state', models.CharField(blank=True, help_text='Estado/Província', max_length=200)),
                ('country', models.CharField(help_text='País', max_length=200)),
                ('latitude', models.FloatField(help_text='Latitude (EPSG:4326)')),
                ('longitude', models.FloatField(help_text='Longitude (EPSG:4326)')),
                ('display_name', models.CharField(help_text='Nome formatado para exibição (ex: São Paulo, SP)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Se é a cidade ativa (para observação)')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant proprietário deste registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(help_text='Usuário que favoritou a cidade', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cidade Favorita',
                'verbose_name_plural': 'Cidades Favoritas',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favoritecidade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'tenant'), name='only_one_active_favorite_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecidade',
            unique_together={('tenant', 'user', 'latitude', 'longitude')},
        ),
    ]
